Mix Model Viewer: mix::containers::tree_node Class Reference
mix::containers::tree_node Class Reference
#include <tree_node.h>
Public Member Functions
tree_node (mix::core::mixGuid key, std::shared_ptr< mix::assetsystem::mixAsset_item > value, tree_node *parent)
tree_node * insert (const mix::core::mixGuid &key, std::shared_ptr< mix::assetsystem::mixAsset_item > child)
std::shared_ptr< mix::assetsystem::mixAsset_item > search_with_guid (const mix::core::mixGuid &key) const
std::shared_ptr< mix::assetsystem::mixAsset_item > search_with_base_name (const std::string &name) const
std::shared_ptr< mix::assetsystem::mixAsset_item > search_with_full_name (const std::string &name) const
std::shared_ptr< mix::assetsystem::mixAsset_item > search_with_path (const std::string &path) const
bool has_children () const
std::vector< std::unique_ptr< tree_node > > & get_children ()
const mix::core::mixGuid & get_key () const
const mix::assetsystem::mixAsset_item * get_value () const
const bool is_root () const
const tree_node * get_parent () const
void print ()
Private Member Functions
template<class T >
std::shared_ptr< mix::assetsystem::mixAsset_item > search_with_member (T val, T(mix::assetsystem::mixAsset_item::*getter)(void) const) const
Static Private Member Functions
static void print_node (tree_node *node, int depth)
Private Attributes
mix::core::mixGuid _key
std::shared_ptr< mix::assetsystem::mixAsset_item > _value
std::vector< std::unique_ptr< tree_node > > _children
tree_node * _parent
Detailed Description
Definition at line 14 of file tree_node.h.
Constructor & Destructor Documentation
tree_node()
mix::containers::tree_node::tree_node (mix::core::mixGuid key, std::shared_ptr< mix::assetsystem::mixAsset_item > value, tree_node * parent) inline
Definition at line 18 of file tree_node.h.
            : _key{ key }, _value{ std::move (value) }, _parent{ parent }
            {
            }
Member Function Documentation
get_children()
std::vector< std::unique_ptr< tree_node > > & mix::containers::tree_node::get_children () inline
Definition at line 35 of file tree_node.h.
            {
                return _children;
            }
References _children.
get_key()
const mix::core::mixGuid & mix::containers::tree_node::get_key () const inline
Definition at line 40 of file tree_node.h.
            {
                return _key;
            }
References _key.
get_parent()
const tree_node * mix::containers::tree_node::get_parent () const inline
Definition at line 55 of file tree_node.h.
            {
                return _parent;
            }
References _parent.
get_value()
const mix::assetsystem::mixAsset_item * mix::containers::tree_node::get_value () const inline
Definition at line 45 of file tree_node.h.
            {
                return _value.get ();
            }
References _value.
has_children()
bool mix::containers::tree_node::has_children () const inline
Definition at line 30 of file tree_node.h.
            {
                return _children.size ();
            }
References _children.
insert()
mix::containers::tree_node * mix::containers::tree_node::insert (const mix::core::mixGuid & key, std::shared_ptr< mix::assetsystem::mixAsset_item > child)
Definition at line 4 of file tree_node.cpp.
{
    size_t index = 0;
    for (; index < _children.size (); index++)
    {
        if (_children.at (index)->get_key () < key)
        {
            break;
        }
    }
    auto it = _children.insert (_children.begin () + index, std::make_unique<tree_node> (key, std::move (child), this));
    return _children.at (index).get ();
}
References _children.
is_root()
const bool mix::containers::tree_node::is_root () const inline
Definition at line 50 of file tree_node.h.
            {
                return _parent == nullptr;
            }
References _parent.
print()
void mix::containers::tree_node::print () inline
Definition at line 60 of file tree_node.h.
            {
                print_node (this, 0);
            }
References print_node().
print_node()
void mix::containers::tree_node::print_node (tree_node * node, int depth) static private
Definition at line 36 of file tree_node.cpp.
{
    std::cout << std::string (depth * 2, '-');
    if (depth > 0)
    {
        std::cout << '>';
    }
    auto val = (*node->_value.get ());
    std::cout << (std::string) val << std::endl;
    for (size_t i = 0; i < node->_children.size (); i++)
    {
        print_node (node->_children.at (i).get (), depth + 1);
    }
}
References _children, and _value.
search_with_base_name()
std::shared_ptr< mix::assetsystem::mixAsset_item > mix::containers::tree_node::search_with_base_name (const std::string & name) const
Definition at line 23 of file tree_node.cpp.
{
    return search_with_member<const std::string&> (name, &mix::assetsystem::mixAsset_item::get_base_name);
}
References mix::assetsystem::mixAsset_item::get_base_name().
search_with_full_name()
std::shared_ptr< mix::assetsystem::mixAsset_item > mix::containers::tree_node::search_with_full_name (const std::string & name) const
Definition at line 27 of file tree_node.cpp.
{
    return search_with_member<const std::string&> (name, &mix::assetsystem::mixAsset_item::get_full_name);
}
References mix::assetsystem::mixAsset_item::get_full_name().
search_with_guid()
std::shared_ptr< mix::assetsystem::mixAsset_item > mix::containers::tree_node::search_with_guid (const mix::core::mixGuid & key) const
Definition at line 18 of file tree_node.cpp.
{
    return search_with_member<const mix::core::mixGuid&> (key, &mix::assetsystem::mixAsset_item::get_guid);
}
References mix::assetsystem::mixAsset_item::get_guid().
search_with_member()
template<class T > std::shared_ptr< mix::assetsystem::mixAsset_item > mix::containers::tree_node::search_with_member (T val, T(mix::assetsystem::mixAsset_item::*)(void) const getter) const inline private
Definition at line 69 of file tree_node.h.
            {
                auto s = std::invoke (getter, _value.get ());
                if (val == s)
                {
                    return _value;
                }
                for (auto&& node : _children)
                {
                    auto s = std::invoke (getter, node->_value.get ());
                    if (val == s)
                    {
                        return node->_value;
                    }
                    auto found = node->search_with_member<T> (val, getter);
                    if (found)
                    {
                        return found;
                    }
                }
                return nullptr;
            }
References _children, and _value.
search_with_path()
std::shared_ptr< mix::assetsystem::mixAsset_item > mix::containers::tree_node::search_with_path (const std::string & path) const
Definition at line 31 of file tree_node.cpp.
{
    return search_with_member<const std::string&> (path, &mix::assetsystem::mixAsset_item::get_path);
}
References mix::assetsystem::mixAsset_item::get_path().
Member Data Documentation
_children
std::vector<std::unique_ptr<tree_node> > mix::containers::tree_node::_children private
Definition at line 98 of file tree_node.h.
_key
mix::core::mixGuid mix::containers::tree_node::_key private
Definition at line 96 of file tree_node.h.
_parent
tree_node* mix::containers::tree_node::_parent private
Definition at line 99 of file tree_node.h.
_value
std::shared_ptr<mix::assetsystem::mixAsset_item> mix::containers::tree_node::_value private
Definition at line 97 of file tree_node.h.
The documentation for this class was generated from the following files:
tree_node.h
tree_node.cpp