Mix Model Viewer: mix::core::mixCamera Class Reference
mix::core::mixCamera Class Reference
#include <mixCamera.h>
Public Member Functions
mixCamera ()
mat4 get_view_mat () const
mat4 get_projection_mat () const
void change_projection (projection_mode p)
void update () override
void debug_input (vec3 v)
void look_at (const vec3 &pos)
virtual void on_gui () override
Public Member Functions inherited from mix::core::mixEntity
mixEntity ()
mixEntity (vec3 pos)
mixEntity (std::string name)
mixEntity (std::string name, vec3 pos)
void add_component (mixComponent *comp)
void set_name (std::string name)
void add_child (std::shared_ptr< mixEntity > ch)
std::string get_name () const
mixEntity * get_parent () const
std::vector< std::shared_ptr< mixEntity > > get_children () const
virtual void update ()
virtual void render (mix::rendering::rendering_context *rendering)
virtual std::string get_gui_name ()=0
virtual void on_gui ()=0
virtual void on_inspector_gui ()=0
virtual void on_scene_gui ()=0
Private Attributes
float _fov { 45.0f }
float movement_speed { 2.0f }
float _sensitivity { 2.0f }
float _zoom { 1.0f }
float _near { 0.01f }
float _far { 1000.0f }
float _aspect { 1024.0f / 768.0f }
projection_mode _projection { projection_mode ::perspective }
Additional Inherited Members
Public Attributes inherited from mix::core::mixEntity
std::unique_ptr< mixTransform > _transform
Protected Member Functions inherited from mix::core::mixEntity
virtual void on_gui () override
virtual void on_inspector_gui () override
virtual void on_scene_gui () override
virtual std::string get_gui_name () override
Protected Attributes inherited from mix::core::mixEntity
bool _is_enabled { true }
bool _is_visible { true }
std::string _name
std::weak_ptr< mixEntity > _parent
std::vector< std::shared_ptr< mixEntity > > _children
std::vector< std::unique_ptr< mixComponent > > _components
Detailed Description
Definition at line 19 of file mixCamera.h.
Constructor & Destructor Documentation
mixCamera()
mix::core::mixCamera::mixCamera ()
Definition at line 3 of file mixCamera.cpp.
                             : mixEntity ()
{
}
Member Function Documentation
change_projection()
void mix::core::mixCamera::change_projection (projection_mode p)
Definition at line 27 of file mixCamera.cpp.
{
    _projection = p;
}
debug_input()
void mix::core::mixCamera::debug_input (vec3 v)
Definition at line 38 of file mixCamera.cpp.
{
    _transform->translate (v * 0.015f);
}
get_projection_mat()
mat4 mix::core::mixCamera::get_projection_mat () const
Definition at line 14 of file mixCamera.cpp.
{
    if (_projection == projection_mode::perspective)
    {
        return perspective (_fov, _aspect, _near, _far);
    }
    else
    {
        return ortho (-5, 5, -5, 5);
    }
}
References ortho(), and mix::core::perspective.
get_view_mat()
mat4 mix::core::mixCamera::get_view_mat () const
Definition at line 7 of file mixCamera.cpp.
{
    auto at = _transform->get_position ();
    auto up = _transform->up ();
    return lookat (at, at + _transform->forward (), up);
}
References lookat().
look_at()
void mix::core::mixCamera::look_at (const vec3 & pos)
Definition at line 43 of file mixCamera.cpp.
{
    _transform->look_at (pos);
}
on_gui()
void mix::core::mixCamera::on_gui () override virtual
Reimplemented from mix::core::mixEntity.
Definition at line 48 of file mixCamera.cpp.
{
}
update()
void mix::core::mixCamera::update () override virtual
Reimplemented from mix::core::mixEntity.
Definition at line 32 of file mixCamera.cpp.
{
    mix::core::mixEntity::update ();
}
References mix::core::mixEntity::update().
Member Data Documentation
_aspect
float mix::core::mixCamera::_aspect { 1024.0f / 768.0f } private
Definition at line 42 of file mixCamera.h.
_far
float mix::core::mixCamera::_far { 1000.0f } private
Definition at line 41 of file mixCamera.h.
_fov
float mix::core::mixCamera::_fov { 45.0f } private
Definition at line 36 of file mixCamera.h.
_near
float mix::core::mixCamera::_near { 0.01f } private
Definition at line 40 of file mixCamera.h.
_projection
projection_mode mix::core::mixCamera::_projection { projection_mode ::perspective } private
Definition at line 44 of file mixCamera.h.
_sensitivity
float mix::core::mixCamera::_sensitivity { 2.0f } private
Definition at line 38 of file mixCamera.h.
_zoom
float mix::core::mixCamera::_zoom { 1.0f } private
Definition at line 39 of file mixCamera.h.
movement_speed
float mix::core::mixCamera::movement_speed { 2.0f } private
Definition at line 37 of file mixCamera.h.
The documentation for this class was generated from the following files:
mixCamera.h
mixCamera.cpp