Mix Model Viewer: mix::platform::platform_utils Class Reference
mix::platform::platform_utils Class Reference
#include <platform_utils.h>
Public Types
enum class search_type { file , folder , all }
Static Public Member Functions
static std::vector< std::string > get_files (const std::string &path, search_type search_type)
static void get_all_dfs (const std::string &root, std::vector< std::string > &list)
static bool is_folder (const std::string &path)
static bool file_exists (const std::string &path)
static bool folder_exists (const std::string &path)
static bool is_file (const std::string &path)
static std::wstring convert_utf8_to_wide (const char *str)
static std::string convert_wide_to_utf8 (const wchar_t *wstr)
static std::string convert_wide_to_ansi (const wchar_t *wstr)
static std::wstring convert_ansi_to_wide (const char *str)
Static Public Attributes
static constexpr size_t max_len = 260
Detailed Description
Definition at line 12 of file platform_utils.h.
Member Enumeration Documentation
search_type
enum class mix::platform::platform_utils::search_type strong
Enumerator
file
folder
all
Definition at line 16 of file platform_utils.h.
            {
                file,
                folder,
                all
            };
Member Function Documentation
convert_ansi_to_wide()
static std::wstring mix::platform::platform_utils::convert_ansi_to_wide (const char * str) inline static
Definition at line 173 of file platform_utils.h.
            {
                std::wstring wstr;
                int result = MultiByteToWideChar (CP_ACP, 0, str, (int) strlen (str), NULL, 0);
                if (result <= 0)
                {
                    auto error = GetLastError ();
                }
                else
                {
                    wstr.resize (result);
                    result = MultiByteToWideChar (CP_ACP, 0, str, (int) strlen (str), &wstr[0], result);
                }
                return wstr;
            }
convert_utf8_to_wide()
static std::wstring mix::platform::platform_utils::convert_utf8_to_wide (const char * str) inline static
Definition at line 120 of file platform_utils.h.
            {
                std::wstring wstr;
                int result = MultiByteToWideChar (CP_UTF8, 0, str, (int) strlen (str), NULL, 0);
                if (result <= 0)
                {
                    auto error = GetLastError ();
                }
                else
                {
                    wstr.resize (result);
                    result = MultiByteToWideChar (CP_UTF8, 0, str, (int) strlen (str), &wstr[0], result);
                }
                return wstr;
            }
convert_wide_to_ansi()
static std::string mix::platform::platform_utils::convert_wide_to_ansi (const wchar_t * wstr) inline static
Definition at line 156 of file platform_utils.h.
            {
                std::string str;
                int result = WideCharToMultiByte (CP_ACP, 0, wstr, (int) wcslen (wstr), NULL, 0, NULL, NULL);
                if (result <= 0)
                {
                    auto error = GetLastError ();
                }
                else
                {
                    str.resize (result);
                    result = WideCharToMultiByte (CP_ACP, 0, wstr, (int) wcslen (wstr), &str[0], result, NULL, NULL);
                }
                return str;
            }
convert_wide_to_utf8()
static std::string mix::platform::platform_utils::convert_wide_to_utf8 (const wchar_t * wstr) inline static
Definition at line 137 of file platform_utils.h.
            {
                std::string str;
                int result = WideCharToMultiByte (CP_UTF8, 0, wstr, (int) wcslen (wstr), NULL, 0, NULL, NULL);
                if (result <= 0)
                {
                    auto error = GetLastError ();
                }
                else
                {
                    str.resize (result);
                    result = WideCharToMultiByte (CP_UTF8, 0, wstr, (int) wcslen (wstr), &str[0], result, NULL, NULL);
                    // CP_UTF8, 0, &str[0], (int)str.size(), NULL, 0)
                }
                return str;
            }
file_exists()
static bool mix::platform::platform_utils::file_exists (const std::string & path) inline static
Definition at line 102 of file platform_utils.h.
            {
                return is_file (path);
            }
References is_file().
folder_exists()
static bool mix::platform::platform_utils::folder_exists (const std::string & path) inline static
Definition at line 107 of file platform_utils.h.
            {
                return is_folder (path);
            }
References is_folder().
get_all_dfs()
static void mix::platform::platform_utils::get_all_dfs (const std::string & root, std::vector< std::string > & list) inline static
Definition at line 60 of file platform_utils.h.
            {
                char p[max_len];
                sprintf_s (p, "%s\\*", root.c_str ());
                std::wstring ws = convert_utf8_to_wide (p);
                WIN32_FIND_DATA data;
                HANDLE hFind = FindFirstFileW (ws.c_str (), &data); // DIRECTORY
                if (hFind != INVALID_HANDLE_VALUE)
                {
                    do
                    {
                        auto is_folder = (data.dwFileAttributes & FILE_ATTRIBUTE_DIRECTORY) != 0;
                        auto path = root + "/" + convert_wide_to_utf8 (data.cFileName);
                        if ((data.dwFileAttributes & INVALID_FILE_ATTRIBUTES) != 0 &&
                            wcscmp (data.cFileName, L".") != 0 && wcscmp (data.cFileName, L"..") != 0)
{
                            if (is_folder)
{
                                list.push_back (path);
                                get_all_dfs (path, list);
                            }
                            else
{
                                list.push_back (path);
                            }
                        }
                    } while (FindNextFileW (hFind, &data));
                    FindClose (hFind);
                }
            }
References convert_utf8_to_wide(), convert_wide_to_utf8(), get_all_dfs(), is_folder(), and max_len.
get_files()
static std::vector< std::string > mix::platform::platform_utils::get_files (const std::string & path, search_type search_type) inline static
Definition at line 23 of file platform_utils.h.
            {
                std::vector<std::string> files;
                char p[max_len];
                sprintf_s (p, "%s\\*", path.c_str ());
                std::wstring ws = convert_utf8_to_wide (p);
                WIN32_FIND_DATA data;
                HANDLE hFind = FindFirstFileW (ws.c_str (), &data); // DIRECTORY
                if (hFind != INVALID_HANDLE_VALUE)
                {
                    do
                    {
                        // TODO: tidy here up...modern cpp...
                        // TODO2: arrange folder creation. Store them as weak ptr in somewhere.
                        auto cond = (search_type == mix::platform::platform_utils::search_type::file &&
                                     (data.dwFileAttributes & FILE_ATTRIBUTE_DIRECTORY) == 0) ||
                                    (search_type == mix::platform::platform_utils::search_type::folder &&
                                     (wcscmp (data.cFileName, L".") != 0 && wcscmp (data.cFileName, L"..") != 0 &&
                                      (data.dwFileAttributes & FILE_ATTRIBUTE_DIRECTORY) != 0)) ||
                                    (wcscmp (data.cFileName, L".") != 0 && wcscmp (data.cFileName, L"..") != 0);
                        if (cond)
{
                            auto p = path + "/" + convert_wide_to_utf8 (data.cFileName);
                            files.emplace_back (p);
                        }
                    } while (FindNextFileW (hFind, &data));
                    FindClose (hFind);
                }
                return files;
            }
References convert_utf8_to_wide(), convert_wide_to_utf8(), file, folder, and max_len.
is_file()
static bool mix::platform::platform_utils::is_file (const std::string & path) inline static
Definition at line 112 of file platform_utils.h.
            {
                auto wide = std::wstring{ path.begin (), path.end () };
                DWORD dwAttrib = GetFileAttributesW (wide.c_str ());
                return (dwAttrib != INVALID_FILE_ATTRIBUTES && !(dwAttrib & FILE_ATTRIBUTE_DIRECTORY));
            }
is_folder()
static bool mix::platform::platform_utils::is_folder (const std::string & path) inline static
Definition at line 95 of file platform_utils.h.
            {
                auto wide = convert_utf8_to_wide (path.c_str ());
                DWORD dwAttrib = GetFileAttributesW (wide.c_str ());
                return (dwAttrib != INVALID_FILE_ATTRIBUTES && (dwAttrib & FILE_ATTRIBUTE_DIRECTORY));
            }
References convert_utf8_to_wide().
Member Data Documentation
max_len
constexpr size_t mix::platform::platform_utils::max_len = 260 static constexpr
Definition at line 22 of file platform_utils.h.
The documentation for this class was generated from the following file:
platform_utils.h