Mix Model Viewer: mix::assetsystem::mixShader Class Reference
mix::assetsystem::mixShader Class Reference
#include <mixShader.h>
Public Member Functions
mixShader (const mix::platform::mixAsset_path &path, const std::string &source, mix::shader::shader_type type)
mixShader (const mix::platform::mixAsset_path &path)
~mixShader ()
void compile (const std::string &source, mix::shader::shader_type type)
const mix::shader::shader_type get_shader_type () const
const unsigned get_shader_id () const
Public Member Functions inherited from mix::assetsystem::mixAsset_item
mixAsset_item (mix::platform::mixAsset_path &&path) noexcept
mixAsset_item (const mix::platform::mixAsset_path &path) noexcept
virtual const std::string & get_base_name () const
virtual const std::string get_shortened_name () const
virtual const std::string & get_full_name () const
virtual const std::string & get_path () const
const std::string & get_extension () const
virtual std::ostream & operator<< (std::ostream &out) const
virtual std::istream & operator>> (std::istream &in) const
virtual operator std::string () const
const mix::core::mixGuid & get_guid () const
Private Attributes
const mix::shader::shader_type _type
unsigned shader_id {}
bool is_compiled
Additional Inherited Members
Protected Attributes inherited from mix::assetsystem::mixAsset_item
bool is_readonly
const mix::core::mixGuid _guid
mix::platform::mixAsset_path _path
Detailed Description
Definition at line 39 of file mixShader.h.
Constructor & Destructor Documentation
mixShader() [1/2]
mix::assetsystem::mixShader::mixShader (const mix::platform::mixAsset_path & path, const std::string & source, mix::shader::shader_type type)
Definition at line 5 of file mixShader.cpp.
: _type{ type }, mix::assetsystem::mixAsset_item (path)
{
    compile (source, _type);
}
References _type, and compile().
mixShader() [2/2]
mix::assetsystem::mixShader::mixShader (const mix::platform::mixAsset_path & path)
Definition at line 11 of file mixShader.cpp.
: _type{ mix::shader::get_shader_type (path.get_extension ()) }, mix::assetsystem::mixAsset_item (path)
{
    auto source = mix::platform::mixFile (path).read_all_text();
    compile (source, _type);
}
References _type, compile(), and mix::platform::mixFile::read_all_text().
~mixShader()
mix::assetsystem::mixShader::~mixShader ()
Definition at line 18 of file mixShader.cpp.
{
    glDeleteShader (shader_id);
}
Member Function Documentation
compile()
void mix::assetsystem::mixShader::compile (const std::string & source, mix::shader::shader_type type)
Definition at line 23 of file mixShader.cpp.
{
    shader_id = glCreateShader ((GLenum)type);
    auto c_source = source.c_str ();
    glShaderSource (shader_id, 1, &c_source, NULL);
    glCompileShader (shader_id);
    // print compile errors if any
    int success;
    char infoLog[512];
    glGetShaderiv (shader_id, GL_COMPILE_STATUS, &success);
    is_compiled = success;
    if (!success)
    {
        //TODO: fallback to shader
        glGetShaderInfoLog (shader_id, 512, NULL, infoLog);
        LOG_ERROR (_path.get_name () + " shader compilation failed!");
    }
}
References LOG_ERROR.
get_shader_id()
const unsigned mix::assetsystem::mixShader::get_shader_id () const
Definition at line 48 of file mixShader.cpp.
{
    return shader_id;
}
get_shader_type()
const mix::shader::shader_type mix::assetsystem::mixShader::get_shader_type () const
Definition at line 43 of file mixShader.cpp.
{
    return _type;
}
Member Data Documentation
_type
const mix::shader::shader_type mix::assetsystem::mixShader::_type private
Definition at line 54 of file mixShader.h.
is_compiled
bool mix::assetsystem::mixShader::is_compiled private
Definition at line 56 of file mixShader.h.
shader_id
unsigned mix::assetsystem::mixShader::shader_id {} private
Definition at line 55 of file mixShader.h.
The documentation for this class was generated from the following files:
mixShader.h
mixShader.cpp