Mix Model Viewer: mix::editor::windows::shortcuts_window Class Reference
mix::editor::windows::shortcuts_window Class Reference
#include <shortcuts_window.h>
Public Member Functions
void render () override
void on_editor_window_size_changed_impl (const vec2i &size) override
shortcuts_window (std::string window_name, mixImGui::window_rect r)
Public Member Functions inherited from mixImGui::gui_window
gui_window (std::string window_name, window_rect r, window_flags flags=window_flags::None)
virtual void render ()
void disable ()
void enable ()
virtual void on_editor_window_size_changed (const vec2i &size)
void set_title (std::string s)
void set_contrainsts (window_rect constraints)
void clear_constraints ()
void set_positioning (window_positioning wp)
Static Public Member Functions
static void initialize (const vec2i &size)
Additional Inherited Members
Protected Member Functions inherited from mixImGui::gui_window
void begin ()
void end () const
void rescale (const vec2i &size)
void set_position (const vec2i &pos)
vec2i get_position () const
vec2i get_size () const
virtual void on_editor_window_size_changed_impl (const vec2i &size)=0
virtual void on_window_resized (const vec2i &old_size, const vec2i &new_size)
window_flags get_flags () const
Protected Attributes inherited from mixImGui::gui_window
bool _is_open = true
std::string _window_name
window_rect _rect
window_rect _constraints
Detailed Description
Definition at line 13 of file shortcuts_window.h.
Constructor & Destructor Documentation
shortcuts_window()
mix::editor::windows::shortcuts_window::shortcuts_window (std::string window_name, mixImGui::window_rect r)
Definition at line 60 of file shortcuts_window.cpp.
: mixImGui::gui_window (window_name,
                        r,
                        mixImGui::window_flags::MenuBar | mixImGui::window_flags::NoCollapse |
                         mixImGui::window_flags::NoMove | mixImGui::window_flags::NoResize)
{
    _styles_editor_tex = mixEditor::get_asset_manager ()->get_asset_with_full_name<mix::assetsystem::mixTexture> ("default_other.png").get();
    assert (_styles_editor_tex);
}
References mix::mixEditor::get_asset_manager(), and mix::assetsystem::mixAsset_manager::get_asset_with_full_name().
Member Function Documentation
initialize()
void mix::editor::windows::shortcuts_window::initialize (const vec2i & size) static
Definition at line 50 of file shortcuts_window.cpp.
{
    auto WINDOW_BEGIN_POS = 0.0f;
    auto WINDOW_SIZE = 0.20f;
    auto rect = mixImGui::window_rect ((int) (size.x * WINDOW_BEGIN_POS), 0, (int) (size.x * WINDOW_SIZE),
                                       static_cast<int> (size.y));
    mixImGui::mixGui::add_window (new editor::windows::shortcuts_window (std::string ("Shortcuts"), rect));
}
References mixImGui::mixGui::add_window().
on_editor_window_size_changed_impl()
void mix::editor::windows::shortcuts_window::on_editor_window_size_changed_impl (const vec2i & size) override virtual
Implements mixImGui::gui_window.
Definition at line 41 of file shortcuts_window.cpp.
{
    auto WINDOW_BEGIN_POS = 0.0f;
    auto WINDOW_SIZE = 0.20f;
    auto width = size.x * WINDOW_SIZE;
    rescale (vec2i (width, static_cast<int> (size.y)));
    set_position (vec2i (size.x * WINDOW_BEGIN_POS, 0));
}
render()
void mix::editor::windows::shortcuts_window::render () override virtual
Reimplemented from mixImGui::gui_window.
Definition at line 3 of file shortcuts_window.cpp.
{
    begin ();
    auto editor = mix::mixEditor::_instance.get ();
    if (editor)
    {
        gui_layout::text_label ("OpenGL Texture Text");
        if (_styles_editor_tex)
        {
            float width = 64;
            float height = 64;
            ImVec2 pos = ImGui::GetCursorScreenPos ();
            //gui_layout::add_image (_styles_editor_tex->get_id(), ImVec2 (pos.x, pos.y), ImVec2 (pos.x + width, pos.y + height), ImVec2 (0, 1), ImVec2 (1, 0));
            if (gui_layout::image_button ("shortcuts-imgui-button", _styles_editor_tex->get_id ()))
            {
                _show_styles_editor = !_show_styles_editor;
            }
            gui_layout::seperator ();
            gui_layout::button ("Label");
            gui_layout::seperator ();
            gui_layout::arrow_button ("Label", 30);
            gui_layout::seperator ();
            gui_layout::small_button ("Label");
            gui_layout::seperator ();
            gui_layout::radio_button ("Label", true);
            if (_show_styles_editor)
            {
                mixGui::show_style_editor (ImGui::GetStyle());
            }
            gui_layout::progress_bar (0.25f);
        }
    }
    end ();
}
References mix::mixEditor::_instance, mixImGui::gui_layout::arrow_button(), mixImGui::gui_window::begin(), mixImGui::gui_layout::button(), mixImGui::gui_window::end(), mixImGui::gui_layout::image_button(), mixImGui::gui_layout::progress_bar(), mixImGui::gui_layout::radio_button(), mixImGui::gui_layout::seperator(), mixImGui::mixGui::show_style_editor(), mixImGui::gui_layout::small_button(), and mixImGui::gui_layout::text_label().
The documentation for this class was generated from the following files:
shortcuts_window.h
shortcuts_window.cpp