Mix Model Viewer: mix::assetsystem::mixTexture Class Reference
mix::assetsystem::mixTexture Class Reference
#include <mixTexture.h>
Public Member Functions
mixTexture (const mix::platform::mixAsset_path &path, texture::texture_type type=texture::texture_type::diffuse)
~mixTexture ()
const mix::texture::texture_type get_texture_type () const
void set_wrapping (texture::texture_wrapping wrapping)
void set_filtering (texture::texture_filtering filtering_min, texture::texture_filtering filtering_mag)
void bind () const
void change_type (mix::texture::texture_type t)
void set_format (mix::texture::texture_format format)
unsigned get_id () const
Public Member Functions inherited from mix::assetsystem::mixAsset_item
mixAsset_item (mix::platform::mixAsset_path &&path) noexcept
mixAsset_item (const mix::platform::mixAsset_path &path) noexcept
virtual const std::string & get_base_name () const
virtual const std::string get_shortened_name () const
virtual const std::string & get_full_name () const
virtual const std::string & get_path () const
const std::string & get_extension () const
virtual std::ostream & operator<< (std::ostream &out) const
virtual std::istream & operator>> (std::istream &in) const
virtual operator std::string () const
const mix::core::mixGuid & get_guid () const
Private Member Functions
void initialize (const mix::platform::mixAsset_path &path, mix::texture::texture_format format)
Private Attributes
unsigned _id
unsigned char * _data
texture::texture_type _type { texture::texture_type::diffuse }
texture::texture_wrapping _wrapping { texture::texture_wrapping ::repeat }
texture::texture_filtering _filtering { texture::texture_filtering ::nearest }
texture::texture_format _format { texture::texture_format ::_default }
Additional Inherited Members
Protected Attributes inherited from mix::assetsystem::mixAsset_item
bool is_readonly
const mix::core::mixGuid _guid
mix::platform::mixAsset_path _path
Detailed Description
Definition at line 73 of file mixTexture.h.
Constructor & Destructor Documentation
mixTexture()
mix::assetsystem::mixTexture::mixTexture (const mix::platform::mixAsset_path & path, texture::texture_type type = texture::texture_type::diffuse)
Definition at line 5 of file mixTexture.cpp.
: _id{ 0 }, _type{ type }, mixAsset_item (path)
{
    _data = nullptr;
    initialize (path, mix::texture::texture_format::rgb);
}
References _data, initialize(), and mix::texture::rgb.
~mixTexture()
mix::assetsystem::mixTexture::~mixTexture ()
Definition at line 12 of file mixTexture.cpp.
{
    stbi_image_free (_data);
    _data = nullptr;
    glDeleteTextures (1, &_id);
}
Member Function Documentation
bind()
void mix::assetsystem::mixTexture::bind () const
Definition at line 31 of file mixTexture.cpp.
{
    glActiveTexture (GL_TEXTURE0 + static_cast<int> (_type));
    glBindTexture (GL_TEXTURE_2D, _id);
}
change_type()
void mix::assetsystem::mixTexture::change_type (mix::texture::texture_type t)
Definition at line 37 of file mixTexture.cpp.
{
    ASSERT (t != _type);
    glDeleteTextures (1, &_id);
    _type = t;
    initialize (_path, _format);
}
References ASSERT.
get_id()
unsigned mix::assetsystem::mixTexture::get_id () const
Definition at line 53 of file mixTexture.cpp.
{
    return _id;
}
get_texture_type()
const mix::texture::texture_type mix::assetsystem::mixTexture::get_texture_type () const inline
Definition at line 80 of file mixTexture.h.
            {
                return _type;
            }
References _type.
initialize()
void mix::assetsystem::mixTexture::initialize (const mix::platform::mixAsset_path & path, mix::texture::texture_format format) private
Definition at line 58 of file mixTexture.cpp.
{
    // TODO: move this to config or something like that
    stbi_set_flip_vertically_on_load (true);
    glGenTextures (1, &_id);
    bind ();
    // set the texture wrapping/filtering options (on the currently bound texture object)
    set_wrapping (texture::texture_wrapping::clamp_to_edge);
    set_filtering (mix::texture::texture_filtering::nearest, mix::texture::texture_filtering::nearest);
    // load and generate the texture
    int width, height, nrChannels;
    if (_data != nullptr)
    {
        stbi_image_free (_data);
        _data = nullptr;
    }
    _data = stbi_load (path.to_cstr (), &width, &height, &nrChannels, 0);
    if (_data)
    {
        unsigned f = nrChannels == 4 ? GL_RGBA : GL_RGB;
        // ASSERT ((format != mix::texture::texture_format::rgb || nrChannels == 3) &&
        //       (format != mix::texture::texture_format::rgb_alpha || nrChannels == 4));
        glTexImage2D (GL_TEXTURE_2D, 0, f, width, height, 0, f, GL_UNSIGNED_BYTE, _data);
        glGenerateMipmap (GL_TEXTURE_2D);
    }
    else
    {
        LOG_ERROR ("Failed to load texture at: " + path.get_name ());
    }
}
References mix::texture::clamp_to_edge, mix::platform::mixAsset_path::get_name(), LOG_ERROR, mix::texture::nearest, and mix::platform::mixAsset_path::to_cstr().
set_filtering()
void mix::assetsystem::mixTexture::set_filtering (texture::texture_filtering filtering_min, texture::texture_filtering filtering_mag)
Definition at line 25 of file mixTexture.cpp.
{
    glTexParameteri (GL_TEXTURE_2D, GL_TEXTURE_MIN_FILTER, static_cast<int> (filtering_min));
    glTexParameteri (GL_TEXTURE_2D, GL_TEXTURE_MAG_FILTER, static_cast<int> (filtering_mag));
}
set_format()
void mix::assetsystem::mixTexture::set_format (mix::texture::texture_format format)
Definition at line 45 of file mixTexture.cpp.
{
    ASSERT (format != _format);
    glDeleteTextures (1, &_id);
    _format = format;
    initialize (_path, _format);
}
References ASSERT.
set_wrapping()
void mix::assetsystem::mixTexture::set_wrapping (texture::texture_wrapping wrapping)
Definition at line 19 of file mixTexture.cpp.
{
    glTexParameteri (GL_TEXTURE_2D, GL_TEXTURE_WRAP_S, static_cast<int> (wrapping));
    glTexParameteri (GL_TEXTURE_2D, GL_TEXTURE_WRAP_T, static_cast<int> (wrapping));
}
Member Data Documentation
_data
unsigned char* mix::assetsystem::mixTexture::_data private
Definition at line 96 of file mixTexture.h.
_filtering
texture::texture_filtering mix::assetsystem::mixTexture::_filtering { texture::texture_filtering ::nearest } private
Definition at line 99 of file mixTexture.h.
_format
texture::texture_format mix::assetsystem::mixTexture::_format { texture::texture_format ::_default } private
Definition at line 100 of file mixTexture.h.
_id
unsigned mix::assetsystem::mixTexture::_id private
Definition at line 95 of file mixTexture.h.
_type
texture::texture_type mix::assetsystem::mixTexture::_type { texture::texture_type::diffuse } private
Definition at line 97 of file mixTexture.h.
_wrapping
texture::texture_wrapping mix::assetsystem::mixTexture::_wrapping { texture::texture_wrapping ::repeat } private
Definition at line 98 of file mixTexture.h.
The documentation for this class was generated from the following files:
mixTexture.h
mixTexture.cpp