Mix Model Viewer: mix::assetsystem::mixAsset_item Class Reference
mix::assetsystem::mixAsset_item Class Reference
Support multiple extensions.
#include <mixAsset_item.h>
Public Member Functions
mixAsset_item (mix::platform::mixAsset_path &&path) noexcept
mixAsset_item (const mix::platform::mixAsset_path &path) noexcept
virtual const std::string & get_base_name () const
virtual const std::string get_shortened_name () const
virtual const std::string & get_full_name () const
virtual const std::string & get_path () const
const std::string & get_extension () const
virtual std::ostream & operator<< (std::ostream &out) const
virtual std::istream & operator>> (std::istream &in) const
virtual operator std::string () const
const mix::core::mixGuid & get_guid () const
Protected Attributes
bool is_readonly
const mix::core::mixGuid _guid
mix::platform::mixAsset_path _path
Detailed Description
Support multiple extensions.
Definition at line 17 of file mixAsset_item.h.
Constructor & Destructor Documentation
mixAsset_item() [1/2]
mix::assetsystem::mixAsset_item::mixAsset_item (mix::platform::mixAsset_path && path) noexcept
Definition at line 7 of file mixAsset_item.cpp.
        : _path{ std::move (path) }, _guid{ mix::core::mixGuid::create_new () }
        {
        }
mixAsset_item() [2/2]
mix::assetsystem::mixAsset_item::mixAsset_item (const mix::platform::mixAsset_path & path) noexcept
Definition at line 11 of file mixAsset_item.cpp.
        : _path{ path }, _guid{ mix::core::mixGuid::create_new () }
        {
        }
Member Function Documentation
get_base_name()
virtual const std::string & mix::assetsystem::mixAsset_item::get_base_name () const inline virtual
Definition at line 24 of file mixAsset_item.h.
            {
                return _path.get_name_without_extension ();
            }
References _path, and mix::platform::mixAsset_path::get_name_without_extension().
get_extension()
const std::string & mix::assetsystem::mixAsset_item::get_extension () const inline
Definition at line 41 of file mixAsset_item.h.
            {
                return _path.get_extension ();
            }
References _path, and mix::platform::mixAsset_path::get_extension().
get_full_name()
virtual const std::string & mix::assetsystem::mixAsset_item::get_full_name () const inline virtual
Definition at line 31 of file mixAsset_item.h.
            {
                return _path.get_name ();
            }
References _path, and mix::platform::mixAsset_path::get_name().
get_guid()
const mix::core::mixGuid & mix::assetsystem::mixAsset_item::get_guid () const inline
Definition at line 54 of file mixAsset_item.h.
            {
                return _guid;
            }
References _guid.
get_path()
virtual const std::string & mix::assetsystem::mixAsset_item::get_path () const inline virtual
Definition at line 36 of file mixAsset_item.h.
            {
                return _path.to_str ();
            }
References _path, and mix::platform::mixAsset_path::to_str().
get_shortened_name()
const std::string mix::assetsystem::mixAsset_item::get_shortened_name () const virtual
Definition at line 15 of file mixAsset_item.cpp.
        {
            std::string name = get_full_name ();
            if (name.size () > 8)
            {
                name = name.substr (0, 8);
                name.append ("...");
            }
            return name;
        }
References get_full_name().
operator std::string()
virtual mix::assetsystem::mixAsset_item::operator std::string () const inline virtual
Definition at line 49 of file mixAsset_item.h.
            {
                return get_base_name ();
            }
References get_base_name().
operator<<()
std::ostream & mix::assetsystem::mixAsset_item::operator<< (std::ostream & out) const virtual
Definition at line 27 of file mixAsset_item.cpp.
        {
            out << get_base_name ();
            return out;
        }
References get_base_name().
operator>>()
std::istream & mix::assetsystem::mixAsset_item::operator>> (std::istream & in) const virtual
Definition at line 32 of file mixAsset_item.cpp.
        {
            auto data = get_base_name ();
            in >> data;
            return in;
        }
References get_base_name().
Member Data Documentation
_guid
const mix::core::mixGuid mix::assetsystem::mixAsset_item::_guid protected
Definition at line 64 of file mixAsset_item.h.
_path
mix::platform::mixAsset_path mix::assetsystem::mixAsset_item::_path protected
Definition at line 66 of file mixAsset_item.h.
is_readonly
bool mix::assetsystem::mixAsset_item::is_readonly protected
Definition at line 63 of file mixAsset_item.h.
The documentation for this class was generated from the following files:
mixAsset_item.h
mixAsset_item.cpp