Mix Model Viewer: mix::assetsystem::loaders::mixAsset_loader_shader Class Reference
mix::assetsystem::loaders::mixAsset_loader_shader Class Reference
#include <mixAsset_loader_shader.h>
Protected Member Functions
mix::assetsystem::mixAsset_item * resolve_impl (mix::platform::mixFile &file) override
virtual mixAsset_item * resolve_impl (mix::platform::mixFile &file)=0
Additional Inherited Members
Public Member Functions inherited from mix::assetsystem::mixAsset_loader_base
mixAsset_loader_base ()
mixAsset_loader_base (mix::assetsystem::asset_processor *processor)
mixAsset_item * resolve (mix::platform::mixFile &file)
void set_asset_processor (mix::assetsystem::asset_processor *processor)
Protected Attributes inherited from mix::assetsystem::mixAsset_loader_base
std::unique_ptr< mix::library::event< mixAsset_item > > _postprocess_item_event
std::unique_ptr< mix::assetsystem::asset_processor > _asset_processor
Detailed Description
Definition at line 12 of file mixAsset_loader_shader.h.
Member Function Documentation
resolve_impl()
mix::assetsystem::mixAsset_item * mix::assetsystem::loaders::mixAsset_loader_shader::resolve_impl (mix::platform::mixFile & file) override protected virtual
Implements mix::assetsystem::mixAsset_loader_base.
Definition at line 10 of file mixAsset_loader_shader.cpp.
            {
                auto type = mix::shader::get_shader_type (file.get_extension());
                return new mix::assetsystem::mixShader (file.get_path (), file.read_all_text (), type);
            }
References mix::platform::mixFile::get_extension(), mix::platform::mixFile::get_path(), mix::shader::get_shader_type(), and mix::platform::mixFile::read_all_text().
The documentation for this class was generated from the following files:
mixAsset_loader_shader.h
mixAsset_loader_shader.cpp