Mix Model Viewer: mix::assetsystem::mixAsset_manager Class Reference
mix::assetsystem::mixAsset_manager Class Reference
#include <mixAsset_manager.h>
Public Member Functions
mixAsset_manager (std::unique_ptr< mix::assetsystem::mixAsset_folder > root)
mixAsset_manager (std::string &root_path)
template<class T >
void register_loader (asset_type type)
template<class T >
void register_loader (asset_type type, asset_processor *processor)
mix::assetsystem::mixAsset_loader_base * get_loader (const asset_type &type) const noexcept
mixAsset_item * resolve_asset (mix::platform::mixFile &file) const noexcept
std::shared_ptr< mixAsset_item > get_asset_with_base_name (const std::string &name) const
template<class T >
std::shared_ptr< T > get_asset_with_base_name (const std::string &name) const
std::shared_ptr< mixAsset_item > get_asset_with_full_name (const std::string &name) const
template<class T >
std::shared_ptr< T > get_asset_with_full_name (const std::string &name) const
std::shared_ptr< mixAsset_item > get_asset_with_path (const std::string &path) const
template<class T >
std::shared_ptr< T > get_asset_with_path (const std::string &name) const
const mix::assetsystem::mixAsset_folder * get_root_folder () const
const asset_tree_ptr get_root_node () const
void debug ()
void resolve_all_assets ()
Static Public Attributes
static mixAsset_manager * instance = nullptr
Private Member Functions
void initialize_default_asset_loaders ()
Static Private Member Functions
static void resolve_assets_impl (const std::string &p, asset_tree_ptr node)
Private Attributes
std::unordered_map< asset_type, std::unique_ptr< mix::assetsystem::mixAsset_loader_base > > _loaders
asset_tree _assets
Detailed Description
Definition at line 29 of file mixAsset_manager.h.
Constructor & Destructor Documentation
mixAsset_manager() [1/2]
mix::assetsystem::mixAsset_manager::mixAsset_manager (std::unique_ptr< mix::assetsystem::mixAsset_folder > root)
Definition at line 15 of file mixAsset_manager.cpp.
        {
            instance = this;
            _assets = std::make_unique<asset_tree_val> (root->get_guid (), std::move (root), nullptr);
            initialize_default_asset_loaders ();
            resolve_all_assets ();
            debug ();
        }
References _assets, debug(), initialize_default_asset_loaders(), instance, and resolve_all_assets().
mixAsset_manager() [2/2]
mix::assetsystem::mixAsset_manager::mixAsset_manager (std::string & root_path)
Definition at line 24 of file mixAsset_manager.cpp.
        {
            instance = this;
            auto root = std::make_unique<mix::assetsystem::mixAsset_folder> (root_path);
            _assets = std::make_unique<asset_tree_val> (root->get_guid (), std::move (root), nullptr);
            initialize_default_asset_loaders ();
            resolve_all_assets ();
            debug ();
        }
References _assets, debug(), initialize_default_asset_loaders(), instance, and resolve_all_assets().
Member Function Documentation
debug()
void mix::assetsystem::mixAsset_manager::debug () inline
Definition at line 93 of file mixAsset_manager.h.
            {
                _assets->print ();
            }
References _assets.
get_asset_with_base_name() [1/2]
std::shared_ptr< mixAsset_item > mix::assetsystem::mixAsset_manager::get_asset_with_base_name (const std::string & name) const inline
Definition at line 60 of file mixAsset_manager.h.
            {
                return _assets->search_with_base_name (name);
            }
References _assets.
get_asset_with_base_name() [2/2]
template<class T > std::shared_ptr< T > mix::assetsystem::mixAsset_manager::get_asset_with_base_name (const std::string & name) const inline
Definition at line 65 of file mixAsset_manager.h.
            {
                return std::static_pointer_cast<T> (_assets->search_with_base_name (name));
            }
References _assets.
get_asset_with_full_name() [1/2]
std::shared_ptr< mixAsset_item > mix::assetsystem::mixAsset_manager::get_asset_with_full_name (const std::string & name) const inline
Definition at line 70 of file mixAsset_manager.h.
            {
                return _assets->search_with_full_name (name);
            }
References _assets.
get_asset_with_full_name() [2/2]
template<class T > std::shared_ptr< T > mix::assetsystem::mixAsset_manager::get_asset_with_full_name (const std::string & name) const inline
Definition at line 75 of file mixAsset_manager.h.
            {
                return std::static_pointer_cast<T> (_assets->search_with_full_name (name));
            }
References _assets.
get_asset_with_path() [1/2]
template<class T > std::shared_ptr< T > mix::assetsystem::mixAsset_manager::get_asset_with_path (const std::string & name) const inline
Definition at line 85 of file mixAsset_manager.h.
            {
                return std::static_pointer_cast<T> (_assets->search_with_path (name));
            }
References _assets.
get_asset_with_path() [2/2]
std::shared_ptr< mixAsset_item > mix::assetsystem::mixAsset_manager::get_asset_with_path (const std::string & path) const inline
Definition at line 80 of file mixAsset_manager.h.
            {
                return _assets->search_with_path (path);
            }
References _assets.
get_loader()
mix::assetsystem::mixAsset_loader_base * mix::assetsystem::mixAsset_manager::get_loader (const asset_type & type) const inline noexcept
Definition at line 49 of file mixAsset_manager.h.
            {
                return _loaders.at (type).get ();
            }
References _loaders.
get_root_folder()
const mix::assetsystem::mixAsset_folder * mix::assetsystem::mixAsset_manager::get_root_folder () const
Definition at line 34 of file mixAsset_manager.cpp.
        {
            return static_cast<const mix::assetsystem::mixAsset_folder*> (_assets->get_value ());
        }
References _assets.
get_root_node()
const asset_tree_ptr mix::assetsystem::mixAsset_manager::get_root_node () const
Definition at line 39 of file mixAsset_manager.cpp.
        {
            return _assets.get ();
        }
References _assets.
initialize_default_asset_loaders()
void mix::assetsystem::mixAsset_manager::initialize_default_asset_loaders () private
Definition at line 79 of file mixAsset_manager.cpp.
        {
            register_loader<mix::assetsystem::loaders::mixAsset_loader_text> (mix::assetsystem::asset_type::Text);
            register_loader<mix::assetsystem::loaders::mixAsset_loader_texture> (
            mix::assetsystem::asset_type::Texture, new mix::assetsystem::default_processors::default_texture_processor ());
            register_loader<mix::assetsystem::loaders::mixAsset_loader_mesh> (mix::assetsystem::asset_type::Material);
            register_loader<mix::assetsystem::loaders::mixAsset_loader_mesh> (mix::assetsystem::asset_type::Mesh);
            register_loader<mix::assetsystem::loaders::mixAsset_loader_text> (mix::assetsystem::asset_type::Other);
            register_loader<mix::assetsystem::loaders::mixAsset_loader_shader> (mix::assetsystem::asset_type::Shader);
            register_loader<mix::assetsystem::loaders::mixAsset_loader_font> (mix::assetsystem::asset_type::Font);
        }
References mix::assetsystem::Font, mix::assetsystem::Material, mix::assetsystem::Mesh, mix::assetsystem::Other, mix::assetsystem::Shader, mix::assetsystem::Text, and mix::assetsystem::Texture.
register_loader() [1/2]
template<class T > void mix::assetsystem::mixAsset_manager::register_loader (asset_type type) inline
Definition at line 37 of file mixAsset_manager.h.
            {
                assert (!_loaders.count (type));
                _loaders.insert ({ type, std::make_unique<T> () });
            }
References _loaders.
register_loader() [2/2]
template<class T > void mix::assetsystem::mixAsset_manager::register_loader (asset_type type, asset_processor * processor) inline
Definition at line 43 of file mixAsset_manager.h.
            {
                assert (!_loaders.count (type));
                _loaders.insert ({ type, std::make_unique<T> (processor) });
            }
References _loaders.
resolve_all_assets()
void mix::assetsystem::mixAsset_manager::resolve_all_assets ()
Definition at line 44 of file mixAsset_manager.cpp.
        {
            INFO (mixAsset_manager::resolve_all_assets);
            auto root =
            static_cast<const mix::assetsystem::mixAsset_folder*> (static_cast<const mixAsset_item*> (_assets->get_value ()));
            resolve_assets_impl (root->get_path_as_str (), _assets.get ());
        }
References _assets, INFO, resolve_all_assets(), and resolve_assets_impl().
resolve_asset()
mixAsset_item * mix::assetsystem::mixAsset_manager::resolve_asset (mix::platform::mixFile & file) const inline noexcept
Definition at line 54 of file mixAsset_manager.h.
            {
                mix::assetsystem::mixAsset_loader_base* loader = get_loader (file.get_asset_type ());
                return loader->resolve (file);
            }
References get_loader(), and mix::assetsystem::mixAsset_loader_base::resolve().
resolve_assets_impl()
void mix::assetsystem::mixAsset_manager::resolve_assets_impl (const std::string & p, asset_tree_ptr node) static private
Definition at line 53 of file mixAsset_manager.cpp.
        {
            // root->get_path_as_str ()
            auto all_paths = mix::platform::platform_utils::get_files (p, mix::platform::platform_utils::search_type::all);
            DEBUG_LOG ("Resolving asset: " + p);
            for (auto path : all_paths)
            {
                if (mix::platform::platform_utils::is_folder (path))
                {
                    auto folder = std::make_shared<mix::assetsystem::mixAsset_folder> (path);
                    auto guid = folder->get_guid ();
                    auto new_node = node->insert (guid, std::move (folder));
                    // TODO: add path join
                    resolve_assets_impl (path, new_node);
                }
                else
                {
                    mix::platform::mixFile file{ path };
                    mixAsset_item* asset = mixAsset_manager::instance->resolve_asset (file);
                    node->insert (asset->get_guid (), std::shared_ptr<mixAsset_item>{ asset });
                    DEBUG_LOG ("\t Adding file: " + path);
                }
            }
        }
References mix::platform::platform_utils::all, DEBUG_LOG, mix::platform::platform_utils::get_files(), mix::assetsystem::mixAsset_item::get_guid(), mix::containers::tree_node::insert(), instance, mix::platform::platform_utils::is_folder(), resolve_asset(), and resolve_assets_impl().
Member Data Documentation
_assets
asset_tree mix::assetsystem::mixAsset_manager::_assets private
Definition at line 105 of file mixAsset_manager.h.
_loaders
std::unordered_map<asset_type, std::unique_ptr<mix::assetsystem::mixAsset_loader_base> > mix::assetsystem::mixAsset_manager::_loaders private
Definition at line 104 of file mixAsset_manager.h.
instance
mixAsset_manager * mix::assetsystem::mixAsset_manager::instance = nullptr static
Definition at line 36 of file mixAsset_manager.h.
The documentation for this class was generated from the following files:
mixAsset_manager.h
mixAsset_manager.cpp