Mix Model Viewer: mix::mixEditor Class Reference
mix::mixEditor Class Reference
#include <mixEditor.h>
Public Member Functions
void run ()
mixEditor ()
void render ()
void init_render_buffers ()
unsigned get_rendered_texture () const
void on_window_size_changed (const vec2i &size)
mix::core::mixWindow * get_window () const
mix::scene_management::mixScene * get_active_scene () const
Static Public Member Functions
static void create_new (editor_config config)
static void destroy ()
static void initialize_asset_manager (std::string path)
static void initialize_gui ()
static mix::assetsystem::mixAsset_manager * get_asset_manager ()
Public Attributes
bool _should_run = false
Static Public Attributes
static std::unique_ptr< mixEditor > _instance = nullptr
Private Member Functions
void gui_pass ()
void start (editor_config config)
Private Attributes
std::unique_ptr< mix::core::mixWindow > _window
std::unique_ptr< mix::containers::frame_buffer > _frame_buffer
std::unique_ptr< mix::rendering::rendering_context > _rendering
std::unique_ptr< mix::scene_management::mixScene > _active_scene
std::unique_ptr< mix::assetsystem::mixAsset_manager > _asset_manager
Detailed Description
Definition at line 14 of file mixEditor.h.
Constructor & Destructor Documentation
mixEditor()
mix::mixEditor::mixEditor ()
Definition at line 23 of file mixEditor.cpp.
                         : _active_scene{ std::make_unique<mix::scene_management::mixScene> () }, _window{ nullptr }
{
}
Member Function Documentation
create_new()
void mix::mixEditor::create_new (editor_config config) static
Definition at line 27 of file mixEditor.cpp.
{
    INFO (mix::mixEditor::create_new);
    mix::mixEditor::_instance = std::make_unique<mix::mixEditor> ();
    mix::mixEditor::_instance->start (config);
}
References _instance, create_new(), and INFO.
destroy()
void mix::mixEditor::destroy () static
Definition at line 34 of file mixEditor.cpp.
{
    mix::mixEditor::_instance.reset ();
}
References _instance.
get_active_scene()
mix::scene_management::mixScene * mix::mixEditor::get_active_scene () const
Definition at line 96 of file mixEditor.cpp.
{
    return _active_scene.get ();
}
get_asset_manager()
mix::assetsystem::mixAsset_manager * mix::mixEditor::get_asset_manager () static
Definition at line 59 of file mixEditor.cpp.
{
    return mix::mixEditor::_instance->_asset_manager.get ();
}
References _instance.
get_rendered_texture()
unsigned mix::mixEditor::get_rendered_texture () const
Definition at line 18 of file mixEditor.cpp.
{
    return _frame_buffer->get_render_texture ();
}
get_window()
mix::core::mixWindow * mix::mixEditor::get_window () const
Definition at line 91 of file mixEditor.cpp.
{
    return _window.get ();
}
gui_pass()
void mix::mixEditor::gui_pass () private
Definition at line 125 of file mixEditor.cpp.
{
    mixImGui::mixGui::render (_frame_buffer.get ());
}
References mixImGui::mixGui::render().
init_render_buffers()
void mix::mixEditor::init_render_buffers ()
Definition at line 12 of file mixEditor.cpp.
{
    auto size = _window->get_window_size ();
    _frame_buffer = std::make_unique<mix::containers::frame_buffer> (static_cast<int> (size.x), static_cast<int> (size.y));
}
References _frame_buffer, and _window.
initialize_asset_manager()
void mix::mixEditor::initialize_asset_manager (std::string path) static
Definition at line 39 of file mixEditor.cpp.
{
    mix::mixEditor::_instance->_asset_manager = std::make_unique<mix::assetsystem::mixAsset_manager> (path);
}
References _instance.
initialize_gui()
void mix::mixEditor::initialize_gui () static
Definition at line 44 of file mixEditor.cpp.
{
    assert (mix::mixEditor::_instance->_asset_manager);
    auto _window = mix::mixEditor::_instance->_window.get();
    mixImGui::mixGui::init (_window->get_glfw_window ());
    mixImGui::mixGui::add_font (mix::mixEditor::_instance->_asset_manager->get_asset_with_full_name<mix::assetsystem::mixFont> ("Raleway-Medium.ttf").get(), true);
    auto w_size = _window->get_window_size ();
    mix::editor::windows::scene_window::initialize (w_size);
    mix::editor::windows::hierarchy_window::initialize (w_size);
    mix::editor::windows::shortcuts_window::initialize (w_size);
    mix::editor::windows::project_window::initialize (w_size);
}
References _instance, mixImGui::mixGui::add_font(), mixImGui::mixGui::init(), mix::editor::windows::hierarchy_window::initialize(), mix::editor::windows::project_window::initialize(), mix::editor::windows::scene_window::initialize(), and mix::editor::windows::shortcuts_window::initialize().
on_window_size_changed()
void mix::mixEditor::on_window_size_changed (const vec2i & size)
Definition at line 117 of file mixEditor.cpp.
{
    _window->on_window_size_changed (size);
    mixImGui::mixGui::on_editor_window_size_changed (size);
    glViewport (0, 0, size.x, size.y);
    _frame_buffer->rescale (size.x, size.y);
}
References mixImGui::mixGui::on_editor_window_size_changed().
render()
void mix::mixEditor::render ()
Definition at line 70 of file mixEditor.cpp.
{
    _frame_buffer->bind ();
    glClearColor (0.9f, 0.9f, 0.9f, 1.0f);
    glClear (GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT | GL_STENCIL_BUFFER_BIT);
    _active_scene->render (_rendering.get ());
    glBindVertexArray (0);
    _frame_buffer->unbind ();
    glClearColor (0.0f, 0.0f, 0.0f, 0.0f);
    glClear (GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT | GL_STENCIL_BUFFER_BIT);
    gui_pass ();
    glfwSwapBuffers (_window->get_glfw_window ());
    glfwPollEvents ();
    glBindVertexArray (0);
}
run()
void mix::mixEditor::run ()
Definition at line 64 of file mixEditor.cpp.
{
    _active_scene->update ();
    _should_run = _window->get_key (GLFW_KEY_ESCAPE) != GLFW_PRESS;
}
start()
void mix::mixEditor::start (editor_config config) private
Definition at line 101 of file mixEditor.cpp.
{
    _window = std::make_unique<mix::core::mixWindow> ();
    _window->initialize (vec2i(1024, 768));
    _window->hide ();
    _window->set_title ("Mix Model Viewer");
    _should_run = true;
    _rendering = std::make_unique<mix::rendering::rendering_context> ();
    _rendering->initialize ();
    glfwSetWindowPosCallback (_window->get_glfw_window (), window_pos_callback);
    glfwSetWindowCloseCallback (_window->get_glfw_window (), window_close_callback);
    glfwSetWindowSizeCallback (_window->get_glfw_window (), window_size_callback);
}
References window_close_callback(), window_pos_callback(), and window_size_callback().
Member Data Documentation
_active_scene
std::unique_ptr<mix::scene_management::mixScene> mix::mixEditor::_active_scene private
Definition at line 44 of file mixEditor.h.
_asset_manager
std::unique_ptr<mix::assetsystem::mixAsset_manager> mix::mixEditor::_asset_manager private
Definition at line 45 of file mixEditor.h.
_frame_buffer
std::unique_ptr<mix::containers::frame_buffer> mix::mixEditor::_frame_buffer private
Definition at line 42 of file mixEditor.h.
_instance
std::unique_ptr< mix::mixEditor > mix::mixEditor::_instance = nullptr static
Definition at line 18 of file mixEditor.h.
_rendering
std::unique_ptr<mix::rendering::rendering_context> mix::mixEditor::_rendering private
Definition at line 43 of file mixEditor.h.
_should_run
bool mix::mixEditor::_should_run = false
Definition at line 25 of file mixEditor.h.
_window
std::unique_ptr<mix::core::mixWindow> mix::mixEditor::_window private
Definition at line 41 of file mixEditor.h.
The documentation for this class was generated from the following files:
mixEditor.h
mixEditor.cpp