Mix Model Viewer: mix::scene_management::mixScene Class Reference
mix::scene_management::mixScene Class Reference
#include <mixScene.h>
Public Member Functions
mixScene ()
mixScene (mix::core::mixEntity *r)
void update ()
void render (mix::rendering::rendering_context *rendering)
void set_parameters (mix::rendering::rendering_context *rendering) const
void add_entity (const std::shared_ptr< mix::core::mixEntity > &entity)
mix::core::mixCamera * get_main_cam () const
mix::core::mixEntity * get_root () const
std::vector< std::weak_ptr< mix::core::light::mixLight > > get_lights () const
Static Public Attributes
static mixScene * _instance = nullptr
Private Attributes
std::vector< std::weak_ptr< mix::core::light::mixLight > > _lights
std::shared_ptr< mix::core::mixCamera > _active_cam
std::unique_ptr< mix::core::mixEntity > _root
Detailed Description
Definition at line 13 of file mixScene.h.
Constructor & Destructor Documentation
mixScene() [1/2]
mix::scene_management::mixScene::mixScene ()
Definition at line 5 of file mixScene.cpp.
                                       : mixScene (new mix::core::mixEntity ("New Scene"))
{
}
mixScene() [2/2]
mix::scene_management::mixScene::mixScene (mix::core::mixEntity * r)
Definition at line 9 of file mixScene.cpp.
{
    _root = std::unique_ptr<mix::core::mixEntity> (r);
    _active_cam = std::make_unique<mix::core::mixCamera> ();
    _active_cam->_transform->set_position (vec3 (0, 0, -15));
    _instance = this;
}
Member Function Documentation
add_entity()
void mix::scene_management::mixScene::add_entity (const std::shared_ptr< mix::core::mixEntity > & entity)
Definition at line 56 of file mixScene.cpp.
{
    get_root ()->add_child (entity);
    if (auto light = std::dynamic_pointer_cast<mix::core::light::mixLight> (entity))
    {
        _lights.push_back (light);
    }
}
get_lights()
std::vector< std::weak_ptr< mix::core::light::mixLight > > mix::scene_management::mixScene::get_lights () const
Definition at line 76 of file mixScene.cpp.
{
    return _lights;
}
get_main_cam()
mix::core::mixCamera * mix::scene_management::mixScene::get_main_cam () const
Definition at line 66 of file mixScene.cpp.
{
    return _active_cam.get();
}
get_root()
mix::core::mixEntity * mix::scene_management::mixScene::get_root () const
Definition at line 71 of file mixScene.cpp.
{
    return _root.get();
}
render()
void mix::scene_management::mixScene::render (mix::rendering::rendering_context * rendering)
Definition at line 23 of file mixScene.cpp.
{
    _root->render (rendering);
}
set_parameters()
void mix::scene_management::mixScene::set_parameters (mix::rendering::rendering_context * rendering) const
Definition at line 28 of file mixScene.cpp.
{
    rendering->set_mat4 ("_view", _active_cam->get_view_mat ());
    rendering->set_mat4 ("_projection", _active_cam->get_projection_mat ());
    rendering->set_vec3 ("_view_pos", _active_cam->_transform->get_position ());
    auto size = _lights.size ();
    rendering->set_1i ("num_lights", static_cast<int> (size));
    for (size_t i = 0; i < size; i++)
    {
        std::weak_ptr<mix::core::light::mixLight> light = _lights.at (0);
        std::string pos = "lights[" + std::to_string (i) + "].position";
        std::string diff = "lights[" + std::to_string (i) + "].diffuse";
        std::string spec = "lights[" + std::to_string (i) + "].specular";
        std::string ambient = "lights[" + std::to_string (i) + "].ambient";
        std::string intensity = "lights[" + std::to_string (i) + "].intensity";
        std::string att = "lights[" + std::to_string (i) + "].attenuation";
        rendering->set_vec3 (pos, light.lock ()->_transform->get_position ());
        rendering->set_vec3 (spec, vec3 (1));
        rendering->set_vec3 (ambient, vec3 (1));
        rendering->set_vec3 (diff, light.lock ()->get_color ());
        rendering->set_1f (intensity, light.lock ()->get_intensity ());
        rendering->set_1f (att, 1.0f);
    }
}
References mix::rendering::rendering_context::set_1f(), mix::rendering::rendering_context::set_1i(), mix::rendering::rendering_context::set_mat4(), and mix::rendering::rendering_context::set_vec3().
update()
void mix::scene_management::mixScene::update ()
Definition at line 17 of file mixScene.cpp.
{
    _active_cam->update ();
    _root->update ();
}
Member Data Documentation
_active_cam
std::shared_ptr<mix::core::mixCamera> mix::scene_management::mixScene::_active_cam private
Definition at line 33 of file mixScene.h.
_instance
mix::scene_management::mixScene * mix::scene_management::mixScene::_instance = nullptr static
Definition at line 19 of file mixScene.h.
_lights
std::vector<std::weak_ptr<mix::core::light::mixLight> > mix::scene_management::mixScene::_lights private
Definition at line 32 of file mixScene.h.
_root
std::unique_ptr<mix::core::mixEntity> mix::scene_management::mixScene::_root private
Definition at line 34 of file mixScene.h.
The documentation for this class was generated from the following files:
mixScene.h
mixScene.cpp