Mix Model Viewer: mixImGui::gui_layout Struct Reference
mixImGui::gui_layout Struct Reference
#include <gui_layout.h>
Static Public Member Functions
static void begin_horizontal (window_rect r=window_rect(static_cast< int >(_cursor.x), static_cast< int >(_cursor.y), 0, 0))
static void end_horizontal ()
static void begin_vertical (window_rect r=window_rect(static_cast< int >(_cursor.x), static_cast< int >(_cursor.y), 0, 0))
static void end_vertical ()
static void text_label (std::string s)
static void begin_selectable_list (i_guielement *previously_selected)
static i_guielement * end_selectable_list ()
static void selectable_image (std::string id, const ImVec2 &size, unsigned image, bool &pressed, bool &double_clicked, bool &right_clicked)
static void render_added_selectables ()
static void add_selectable (i_guielement *element)
static void begin_child (std::string s)
static void begin_child (std::string s, const ImVec2 &size, bool border=true, int flags=0)
static void end_child ()
static void add_image (unsigned texture_id, const ImVec2 &size, const ImVec2 &uv_min, const ImVec2 &uv_max, const ImVec4 &tint_color=ImVec4(1, 1, 1, 1), const ImVec4 &border_color=ImVec4(0, 0, 0, 0))
static void slider_float (const char *label, float *value, float min, float max)
static void collapsing_label (std::string s, bool *is_visible)
static void horizontal_space (float space)
static void vertical_space (float space)
static void new_line ()
static void seperator ()
static void progress_bar (float r)
static bool button (const std::string &label, const ImVec2 &size=ImVec2(32, 32))
static bool radio_button (const std::string &label, bool is_active)
static bool small_button (const std::string &label)
static bool arrow_button (const std::string &label, int dir)
static bool image_button (const std::string &str_id, unsigned user_texture_id, const ImVec2 &size=ImVec2(32, 32), const ImVec2 &uv0=ImVec2(0, 0), const ImVec2 &uv1=ImVec2(1, 1), const ImVec4 &bg_col=ImVec4(0, 0, 0, 0), const ImVec4 &tint_col=ImVec4(0, 0, 0, 0))
static bool is_double_clicked ()
static bool is_left_clicked ()
static bool is_right_clicked ()
static void begin_context_menu (const std::string &id)
static void end_context_menu ()
static bool tree_node (const char *label, int index, bool is_selected=false, bool is_framed=false, bool is_leaf=false)
static bool tree_node (const char *label)
static void tree_pop ()
static bool begin_drag_drop_source ()
static void end_drag_drop_source ()
static bool set_drag_drop_payload (const char *label, const void *data, size_t size)
static bool begin_drag_drop_target ()
static void end_drag_drop_target ()
static void * accept_drag_drop_payload (const char *label)
static void set_background_color (mix::math::color &color)
static void pop_style_vars ()
static ImVec2 get_cursor ()
template<class T >
static T * get_top_block ()
static gui_layout * get_top_block ()
Protected Member Functions
gui_layout (mixImGui::layout_type new_layout, window_rect r)
Static Protected Member Functions
static void begin_vertical_selectable (window_rect r=window_rect(static_cast< int >(_cursor.x), static_cast< int >(_cursor.y), 0, 0))
static void end_vertical_selectable ()
Private Member Functions
void before_render ()
void after_render ()
mixImGui::layout_type get_layout () const
mixImGui::layout_type get_previous_layout () const
Static Private Member Functions
static void set_global_layout (mixImGui::layout_type new_layout)
static void add_block (gui_layout *layout)
static void end_current_block (mixImGui::layout_type target_layout)
static bool selectable_text (std::string label, bool is_selected)
Private Attributes
window_rect _rect
mixImGui::layout_type _current_layout
mixImGui::layout_type _last_layout
int _render_index
Static Private Attributes
static ImVec2 _cursor = ImVec2 ()
static mixImGui::layout_type _global_layout = mixImGui::layout_type::vertical
static std::stack< std::unique_ptr< gui_layout > > _layouts
Detailed Description
Definition at line 49 of file gui_layout.h.
Constructor & Destructor Documentation
gui_layout()
mixImGui::gui_layout::gui_layout (mixImGui::layout_type new_layout, window_rect r) protected
Definition at line 9 of file gui_layout.cpp.
{
    _rect = r;
    _current_layout = new_layout;
    _last_layout = _global_layout;
    _cursor = ImGui::GetCursorPos ();
    _render_index = 0;
}
References _current_layout, _cursor, _global_layout, _last_layout, _rect, and _render_index.
Member Function Documentation
accept_drag_drop_payload()
void * mixImGui::gui_layout::accept_drag_drop_payload (const char * label) static
Definition at line 311 of file gui_layout.cpp.
{
    auto payload = ImGui::AcceptDragDropPayload (label);
    if (payload != nullptr)
    {
        return payload->Data;
    }
    return nullptr;
}
add_block()
void mixImGui::gui_layout::add_block (mixImGui::gui_layout * layout) static private
Definition at line 434 of file gui_layout.cpp.
{
    mixImGui::gui_layout::_layouts.push (std::unique_ptr<mixImGui::gui_layout> (layout));
    set_global_layout (layout->get_layout ());
}
References _layouts, and get_layout().
add_image()
void mixImGui::gui_layout::add_image (unsigned texture_id, const ImVec2 & size, const ImVec2 & uv_min, const ImVec2 & uv_max, const ImVec4 & tint_color = ImVec4 (1, 1, 1, 1), const ImVec4 & border_color = ImVec4(0, 0, 0, 0)) static
Definition at line 95 of file gui_layout.cpp.
{
    auto block = mixImGui::gui_layout::get_top_block ();
    block->before_render ();
    ImGui::Image ((void*) (intptr_t) texture_id, size, uv_min, uv_max, tint_color, border_color);
    block->after_render ();
}
References get_top_block().
add_selectable()
void mixImGui::gui_layout::add_selectable (i_guielement * element) static
Definition at line 160 of file gui_layout.cpp.
{
    auto block = mixImGui::gui_layout::get_top_block<mixImGui::gui_selectable_layout> ();
    block->_selectables.push_back (element);
}
after_render()
void mixImGui::gui_layout::after_render () private
Definition at line 399 of file gui_layout.cpp.
{
    _render_index++;
    auto last_item_size = ImGui::GetItemRectSize ();
    if (_current_layout == layout_type::vertical)
    {
        _rect._h += (int) last_item_size.y;
        _rect._w = std::max ((int) last_item_size.y, _rect._w);
        _cursor.y += (int) last_item_size.y;
    }
    else
    {
        _rect._w += (int) last_item_size.x;
        _rect._h = std::max ((int) last_item_size.x, _rect._h);
        _cursor.x += (int) last_item_size.x;
    }
    ImGui::SetCursorPos (_cursor);
}
References mixImGui::vertical.
arrow_button()
bool mixImGui::gui_layout::arrow_button (const std::string & label, int dir) static
Definition at line 202 of file gui_layout.cpp.
{
    auto block = mixImGui::gui_layout::get_top_block ();
    block->before_render ();
    bool result = ImGui::ArrowButton (label.c_str (), dir);
    block->after_render ();
    return result;
}
References get_top_block().
before_render()
void mixImGui::gui_layout::before_render () private
Definition at line 378 of file gui_layout.cpp.
{
    auto w_size = ImGui::GetWindowSize ();
    auto w_pos = ImGui::GetWindowPos ();
    auto cursor_pos = ImGui::GetCursorPos ();
    // ImGui::SetCursorPos (ImVec2 (_local_cursor.x + _cursor.x, _local_cursor.y + _cursor.y));
    if (_global_layout == mixImGui::layout_type::horizontal)
    {
        if (_render_index > 0)
        {
            auto last_item_size = ImGui::GetItemRectSize ();
            _cursor.x += (int) last_item_size.x;
            ImGui::SetCursorPos (_cursor);
        }
    }
    // command ();
}
References mixImGui::horizontal.
begin_child() [1/2]
void mixImGui::gui_layout::begin_child (std::string s) static
Definition at line 80 of file gui_layout.cpp.
{
    ImGui::BeginChild (s.c_str ());
}
begin_child() [2/2]
void mixImGui::gui_layout::begin_child (std::string s, const ImVec2 & size, bool border = true, int flags = 0) static
Definition at line 85 of file gui_layout.cpp.
{
    ImGui::BeginChild (s.c_str (), size, border, flags);
}
begin_context_menu()
void mixImGui::gui_layout::begin_context_menu (const std::string & id) static
Definition at line 244 of file gui_layout.cpp.
{
    ImGui::OpenPopup (id.c_str ());
}
begin_drag_drop_source()
bool mixImGui::gui_layout::begin_drag_drop_source () static
Definition at line 286 of file gui_layout.cpp.
{
    return ImGui::BeginDragDropSource ();
}
begin_drag_drop_target()
bool mixImGui::gui_layout::begin_drag_drop_target () static
Definition at line 301 of file gui_layout.cpp.
{
    return ImGui::BeginDragDropTarget();
}
begin_horizontal()
void mixImGui::gui_layout::begin_horizontal (window_rect r = window_rect (static_cast<int> (_cursor.x), static_cast<int> (_cursor.y), 0, 0)) static
Definition at line 18 of file gui_layout.cpp.
{
    add_block (new mixImGui::gui_layout (mixImGui::layout_type::horizontal, r));
}
References mixImGui::horizontal.
begin_selectable_list()
void mixImGui::gui_layout::begin_selectable_list (i_guielement * previously_selected) static
Definition at line 57 of file gui_layout.cpp.
{
    begin_vertical_selectable ();
    auto block = mixImGui::gui_layout::get_top_block<mixImGui::gui_selectable_layout> ();
    block->_selected = previously_selected;
}
begin_vertical()
void mixImGui::gui_layout::begin_vertical (window_rect r = window_rect (static_cast<int> (_cursor.x), static_cast<int> (_cursor.y), 0, 0)) static
Definition at line 28 of file gui_layout.cpp.
{
    add_block (new mixImGui::gui_layout (mixImGui::layout_type::vertical, r));
}
References mixImGui::vertical.
begin_vertical_selectable()
void mixImGui::gui_layout::begin_vertical_selectable (window_rect r = window_rect (static_cast<int> (_cursor.x), static_cast<int> (_cursor.y), 0, 0)) static protected
Definition at line 38 of file gui_layout.cpp.
{
    add_block (new mixImGui::gui_selectable_layout (mixImGui::layout_type::vertical, r));
}
References mixImGui::vertical.
button()
bool mixImGui::gui_layout::button (const std::string & label, const ImVec2 & size = ImVec2 (32, 32)) static
Definition at line 193 of file gui_layout.cpp.
{
    auto block = mixImGui::gui_layout::get_top_block ();
    block->before_render ();
    bool result = ImGui::Button (label.c_str (), size);
    block->after_render ();
    return result;
}
References get_top_block().
collapsing_label()
void mixImGui::gui_layout::collapsing_label (std::string s, bool * is_visible) static
Definition at line 339 of file gui_layout.cpp.
{
    auto block = mixImGui::gui_layout::get_top_block ();
    block->before_render ();
    *is_visible = ImGui::CollapsingHeader (s.c_str (), ImGuiTreeNodeFlags_Framed | ImGuiTreeNodeFlags_DefaultOpen);
    block->after_render ();
}
References get_top_block().
end_child()
void mixImGui::gui_layout::end_child () static
Definition at line 90 of file gui_layout.cpp.
{
    ImGui::EndChild ();
}
end_context_menu()
void mixImGui::gui_layout::end_context_menu () static
Definition at line 249 of file gui_layout.cpp.
{
    ImGui::EndPopup ();
}
end_current_block()
void mixImGui::gui_layout::end_current_block (mixImGui::layout_type target_layout) static private
Definition at line 440 of file gui_layout.cpp.
{
    auto block = mixImGui::gui_layout::get_top_block ();
    assert (block->get_layout () == target_layout);
    auto cursor_pos = ImGui::GetCursorPos ();
    if (block->_last_layout == layout_type::horizontal)
    {
        _cursor = ImVec2 ((float) block->_rect._x + block->_rect._w, (float) block->_rect._y);
    }
    else
    {
        _cursor = ImVec2 ((float) block->_rect._x, (float) block->_rect._y + block->_rect._h);
    }
    ImGui::SetCursorPos (_cursor);
    set_global_layout (block->get_previous_layout ());
    mixImGui::gui_layout::_layouts.pop ();
    if (_layouts.size () == 0)
    {
        _cursor = ImVec2 ();
    }
}
References _layouts, get_top_block(), and mixImGui::horizontal.
end_drag_drop_source()
void mixImGui::gui_layout::end_drag_drop_source () static
Definition at line 291 of file gui_layout.cpp.
{
    ImGui::EndDragDropSource ();
}
end_drag_drop_target()
void mixImGui::gui_layout::end_drag_drop_target () static
Definition at line 306 of file gui_layout.cpp.
{
    ImGui::EndDragDropTarget ();
}
end_horizontal()
void mixImGui::gui_layout::end_horizontal () static
Definition at line 23 of file gui_layout.cpp.
{
    end_current_block (mixImGui::layout_type::horizontal);
}
References mixImGui::horizontal.
end_selectable_list()
mixImGui::i_guielement * mixImGui::gui_layout::end_selectable_list () static
Definition at line 64 of file gui_layout.cpp.
{
    auto block = mixImGui::gui_layout::get_top_block<mixImGui::gui_selectable_layout> ();
    if (block->_last_selectable_index != block->_selectables.size ())
    {
        render_added_selectables ();
    }
    i_guielement* selected = block->_selected;
    end_vertical_selectable ();
    return selected;
}
end_vertical()
void mixImGui::gui_layout::end_vertical () static
Definition at line 33 of file gui_layout.cpp.
{
    end_current_block (mixImGui::layout_type::vertical);
}
References mixImGui::vertical.
end_vertical_selectable()
void mixImGui::gui_layout::end_vertical_selectable () static protected
Definition at line 43 of file gui_layout.cpp.
{
    end_vertical ();
}
get_cursor()
ImVec2 mixImGui::gui_layout::get_cursor () static
Definition at line 334 of file gui_layout.cpp.
{
    return _cursor;
}
get_layout()
mixImGui::layout_type mixImGui::gui_layout::get_layout () const private
Definition at line 419 of file gui_layout.cpp.
{
    return _current_layout;
}
get_previous_layout()
mixImGui::layout_type mixImGui::gui_layout::get_previous_layout () const private
Definition at line 424 of file gui_layout.cpp.
{
    return _last_layout;
}
get_top_block() [1/2]
template<class T > static T * mixImGui::gui_layout::get_top_block () inline static
Definition at line 126 of file gui_layout.h.
        {
            if (!mixImGui::gui_layout::_layouts.empty ())
            {
                return static_cast<T*> (mixImGui::gui_layout::_layouts.top ().get ());
            }
            return nullptr;
        }
References _layouts.
get_top_block() [2/2]
static gui_layout * mixImGui::gui_layout::get_top_block () inline static
Definition at line 136 of file gui_layout.h.
        {
            //assert (!mixImGui::gui_layout::_layouts.empty ());
            if (!mixImGui::gui_layout::_layouts.empty ())
            {
                return mixImGui::gui_layout::_layouts.top ().get ();
            }
            return nullptr;
        }
References _layouts.
horizontal_space()
void mixImGui::gui_layout::horizontal_space (float space) static
Definition at line 357 of file gui_layout.cpp.
{
    _cursor = ImVec2 (_cursor.x + space, _cursor.y);
    ImGui::SetCursorPos (_cursor);
}
image_button()
bool mixImGui::gui_layout::image_button (const std::string & str_id, unsigned user_texture_id, const ImVec2 & size = ImVec2 (32, 32), const ImVec2 & uv0 = ImVec2 (0, 0), const ImVec2 & uv1 = ImVec2 (1, 1), const ImVec4 & bg_col = ImVec4 (0, 0, 0, 0), const ImVec4 & tint_col = ImVec4 (0, 0, 0, 0)) static
Definition at line 229 of file gui_layout.cpp.
{
    auto block = mixImGui::gui_layout::get_top_block ();
    block->before_render ();
    bool result = ImGui::ImageButton (str_id.c_str (), (void*) (intptr_t) (user_texture_id), size, uv0, uv1, bg_col, tint_col);
    block->after_render ();
    return result;
}
References get_top_block().
is_double_clicked()
bool mixImGui::gui_layout::is_double_clicked () static
Definition at line 119 of file gui_layout.cpp.
{
    return ImGui::IsItemHovered () && ImGui::IsMouseDoubleClicked (0);
}
is_left_clicked()
bool mixImGui::gui_layout::is_left_clicked () static
Definition at line 124 of file gui_layout.cpp.
{
    return ImGui::IsItemHovered () && ImGui::IsMouseClicked (0);
}
is_right_clicked()
bool mixImGui::gui_layout::is_right_clicked () static
Definition at line 130 of file gui_layout.cpp.
{
    return ImGui::IsItemHovered () && ImGui::IsMouseClicked (1);
}
new_line()
void mixImGui::gui_layout::new_line () static
Definition at line 368 of file gui_layout.cpp.
{
    ImGui::NewLine ();
}
pop_style_vars()
void mixImGui::gui_layout::pop_style_vars () static
Definition at line 328 of file gui_layout.cpp.
{
    ImGui::PopStyleColor ();
}
progress_bar()
void mixImGui::gui_layout::progress_bar (float r) static
Definition at line 185 of file gui_layout.cpp.
{
    auto block = mixImGui::gui_layout::get_top_block ();
    block->before_render ();
    ImGui::ProgressBar (r);
    block->after_render ();
}
References get_top_block().
radio_button()
bool mixImGui::gui_layout::radio_button (const std::string & label, bool is_active) static
Definition at line 220 of file gui_layout.cpp.
{
    auto block = mixImGui::gui_layout::get_top_block ();
    block->before_render ();
    bool result = ImGui::RadioButton (label.c_str (), is_active);
    block->after_render ();
    return result;
}
References get_top_block().
render_added_selectables()
void mixImGui::gui_layout::render_added_selectables () static
Definition at line 166 of file gui_layout.cpp.
{
    auto block = mixImGui::gui_layout::get_top_block<mixImGui::gui_selectable_layout> ();
    auto start_index = block->_last_selectable_index;
    size_t i;
    for (i = start_index; i < block->_selectables.size (); i++)
    {
        auto element = block->_selectables.at (i);
        //gui_layout::horizontal_space (20);
        bool selected = element == block->_selected;
        if (gui_layout::selectable_text (element->get_gui_name (), selected))
        {
            block->_selected = element;
        }
    }
    block->_last_selectable_index = static_cast<int> (i);
}
References selectable_text().
selectable_image()
void mixImGui::gui_layout::selectable_image (std::string id, const ImVec2 & size, unsigned image, bool & pressed, bool & double_clicked, bool & right_clicked) static
Definition at line 135 of file gui_layout.cpp.
    {
    auto block = mixImGui::gui_layout::_layouts.top ().get ();
    block->before_render ();
    auto cursor = ImGui::GetCursorPos ();
    auto header_hover_col = ImGui::GetStyleColorVec4 (ImGuiCol_HeaderHovered);
    auto header_active_col = ImGui::GetStyleColorVec4 (ImGuiCol_HeaderActive);
    auto header_normal_col = ImGui::GetStyleColorVec4 (ImGuiCol_Header);
    ImGui::PushStyleColor (ImGuiCol_HeaderHovered, ImVec4 ());
    ImGui::PushStyleColor (ImGuiCol_HeaderActive, ImVec4 ());
    pressed = ImGui::Selectable ((std::string ("##") + id).c_str (), false,
                                      ImGuiSelectableFlags_DontClosePopups | ImGuiSelectableFlags_AllowDoubleClick, size);
    double_clicked = is_double_clicked ();
    right_clicked = is_right_clicked ();
    ImGui::PopStyleColor (2);
    ImGui::SetCursorPos (cursor);
    {
        add_image (image, size, ImVec2 (0, 1), ImVec2 (1, 0));
    }
    block->after_render ();
}
References _layouts.
selectable_text()
bool mixImGui::gui_layout::selectable_text (std::string label, bool is_selected) static private
Definition at line 109 of file gui_layout.cpp.
{
    auto block = mixImGui::gui_layout::_layouts.top ().get ();
    block->before_render ();
    bool pressed = ImGui::Selectable (label.c_str (), is_selected,
                                      ImGuiSelectableFlags_DontClosePopups | ImGuiSelectableFlags_AllowDoubleClick);
    block->after_render ();
    return pressed;
}
References _layouts.
seperator()
void mixImGui::gui_layout::seperator () static
Definition at line 373 of file gui_layout.cpp.
{
    ImGui::Separator ();
}
set_background_color()
void mixImGui::gui_layout::set_background_color (mix::math::color & color) static
Definition at line 321 of file gui_layout.cpp.
{
    vec4 c = color.get_value();
    ImVec4 imgui_color = ImVec4 (c.x, c.y, c.z, c.w);
    ImGui::PushStyleColor (ImGuiCol_WindowBg, imgui_color);
}
References mix::math::color::get_value().
set_drag_drop_payload()
bool mixImGui::gui_layout::set_drag_drop_payload (const char * label, const void * data, size_t size) static
Definition at line 296 of file gui_layout.cpp.
{
    return ImGui::SetDragDropPayload (label, data, size);
}
set_global_layout()
void mixImGui::gui_layout::set_global_layout (mixImGui::layout_type new_layout) static private
Definition at line 429 of file gui_layout.cpp.
{
    _global_layout = new_layout;
}
slider_float()
void mixImGui::gui_layout::slider_float (const char * label, float * value, float min, float max) static
Definition at line 348 of file gui_layout.cpp.
{
    auto block = mixImGui::gui_layout::get_top_block ();
    block->before_render ();
    ImGui::SliderFloat (label, value, min, max);
    block->after_render ();
}
References get_top_block().
small_button()
bool mixImGui::gui_layout::small_button (const std::string & label) static
Definition at line 211 of file gui_layout.cpp.
{
    auto block = mixImGui::gui_layout::get_top_block ();
    block->before_render ();
    bool result = ImGui::SmallButton (label.c_str ());
    block->after_render ();
    return result;
}
References get_top_block().
text_label()
void mixImGui::gui_layout::text_label (std::string s) static
Definition at line 49 of file gui_layout.cpp.
{
    auto block = mixImGui::gui_layout::get_top_block ();
    block->before_render ();
    ImGui::Text (s.c_str ());
    block->after_render ();
}
References get_top_block().
tree_node() [1/2]
bool mixImGui::gui_layout::tree_node (const char * label) static
Definition at line 276 of file gui_layout.cpp.
{
    return ImGui::TreeNode (label);
}
tree_node() [2/2]
bool mixImGui::gui_layout::tree_node (const char * label, int index, bool is_selected = false, bool is_framed = false, bool is_leaf = false) static
Definition at line 254 of file gui_layout.cpp.
{
    ImGuiTreeNodeFlags flags = ImGuiTreeNodeFlags_SpanAvailWidth | ImGuiTreeNodeFlags_OpenOnArrow;
    if (is_selected)
    {
        flags |= ImGuiTreeNodeFlags_Selected;
    }
    if (is_framed)
    {
        flags |= ImGuiTreeNodeFlags_Framed | ImGuiTreeNodeFlags_CollapsingHeader;
    }
    if (is_leaf)
    {
        flags |= ImGuiTreeNodeFlags_Leaf | ImGuiTreeNodeFlags_NoTreePushOnOpen;
    }
    return ImGui::TreeNodeEx ((void*) (intptr_t) index, flags, label);
}
tree_pop()
void mixImGui::gui_layout::tree_pop () static
Definition at line 281 of file gui_layout.cpp.
{
    ImGui::TreePop();
}
vertical_space()
void mixImGui::gui_layout::vertical_space (float space) static
Definition at line 363 of file gui_layout.cpp.
{
    ImGui::Dummy (ImVec2 (0.0f, space));
}
Member Data Documentation
_current_layout
mixImGui::layout_type mixImGui::gui_layout::_current_layout private
Definition at line 170 of file gui_layout.h.
_cursor
ImVec2 mixImGui::gui_layout::_cursor = ImVec2 () static private
Definition at line 159 of file gui_layout.h.
_global_layout
mixImGui::layout_type mixImGui::gui_layout::_global_layout = mixImGui::layout_type::vertical static private
Definition at line 160 of file gui_layout.h.
_last_layout
mixImGui::layout_type mixImGui::gui_layout::_last_layout private
Definition at line 171 of file gui_layout.h.
_layouts
std::stack< std::unique_ptr< mixImGui::gui_layout > > mixImGui::gui_layout::_layouts static private
Definition at line 161 of file gui_layout.h.
_rect
window_rect mixImGui::gui_layout::_rect private
Definition at line 169 of file gui_layout.h.
_render_index
int mixImGui::gui_layout::_render_index private
Definition at line 172 of file gui_layout.h.
The documentation for this struct was generated from the following files:
gui_layout.h
gui_layout.cpp