Mix Model Viewer: mix::core::mixEntity Class Reference
mix::core::mixEntity Class Reference
#include <mixEntity.h>
Public Member Functions
mixEntity ()
mixEntity (vec3 pos)
mixEntity (std::string name)
mixEntity (std::string name, vec3 pos)
void add_component (mixComponent *comp)
void set_name (std::string name)
void add_child (std::shared_ptr< mixEntity > ch)
std::string get_name () const
mixEntity * get_parent () const
std::vector< std::shared_ptr< mixEntity > > get_children () const
virtual void update ()
virtual void render (mix::rendering::rendering_context *rendering)
virtual std::string get_gui_name ()=0
virtual void on_gui ()=0
virtual void on_inspector_gui ()=0
virtual void on_scene_gui ()=0
Public Attributes
std::unique_ptr< mixTransform > _transform
Protected Member Functions
virtual void on_gui () override
virtual void on_inspector_gui () override
virtual void on_scene_gui () override
virtual std::string get_gui_name () override
Protected Attributes
bool _is_enabled { true }
bool _is_visible { true }
std::string _name
std::weak_ptr< mixEntity > _parent
std::vector< std::shared_ptr< mixEntity > > _children
std::vector< std::unique_ptr< mixComponent > > _components
Detailed Description
Definition at line 18 of file mixEntity.h.
Constructor & Destructor Documentation
mixEntity() [1/4]
mix::core::mixEntity::mixEntity ()
Definition at line 4 of file mixEntity.cpp.
                             : mixEntity ("Entity")
{
}
mixEntity() [2/4]
mix::core::mixEntity::mixEntity (vec3 pos)
Definition at line 8 of file mixEntity.cpp.
                                     : mixEntity ("Entity", pos)
{
}
mixEntity() [3/4]
mix::core::mixEntity::mixEntity (std::string name)
Definition at line 12 of file mixEntity.cpp.
                                           : mixEntity (name, vec3 (0))
{
}
mixEntity() [4/4]
mix::core::mixEntity::mixEntity (std::string name, vec3 pos)
Definition at line 16 of file mixEntity.cpp.
                                                     : _name{ name }
{
    _transform = std::make_unique<mix::core::mixTransform> (pos);
    _transform->set_position (pos);
}
References _transform.
Member Function Documentation
add_child()
void mix::core::mixEntity::add_child (std::shared_ptr< mixEntity > ch)
Definition at line 27 of file mixEntity.cpp.
{
    _children.emplace_back (std::move (ch));
}
add_component()
void mix::core::mixEntity::add_component (mixComponent * comp)
Definition at line 22 of file mixEntity.cpp.
{
    _components.emplace_back (std::unique_ptr<mix::components::mixComponent> (comp));
}
get_children()
std::vector< std::shared_ptr< mix::core::mixEntity > > mix::core::mixEntity::get_children () const
Definition at line 47 of file mixEntity.cpp.
{
    return _children;
}
get_gui_name()
std::string mix::core::mixEntity::get_gui_name () override protected virtual
Implements mixImGui::i_guielement.
Definition at line 117 of file mixEntity.cpp.
{
    return get_name ();
}
get_name()
std::string mix::core::mixEntity::get_name () const
Definition at line 32 of file mixEntity.cpp.
{
    return _name;
}
get_parent()
mix::core::mixEntity * mix::core::mixEntity::get_parent () const
Definition at line 37 of file mixEntity.cpp.
{
    if (_parent.expired())
    {
        return nullptr;
    }
    return _parent.lock ().get ();
}
on_gui()
void mix::core::mixEntity::on_gui () override protected virtual
Implements mixImGui::i_guielement.
Reimplemented in mix::core::mixCamera.
Definition at line 90 of file mixEntity.cpp.
{
    mixImGui::gui_layout::begin_vertical ();
    mixImGui::gui_layout::text_label (get_name ());
    mixImGui::gui_layout::begin_horizontal ();
    mixImGui::gui_layout::text_label ("Position: ");
    mixImGui::gui_layout::horizontal_space(10);
    auto pos = _transform->get_position();
    mixImGui::gui_layout::text_label ("X: ");
    mixImGui::gui_layout::text_label (std::to_string(pos.x));
    mixImGui::gui_layout::text_label ("Y: ");
    mixImGui::gui_layout::text_label (std::to_string (pos.y));
    mixImGui::gui_layout::text_label ("Z: ");
    mixImGui::gui_layout::text_label (std::to_string (pos.z));
    mixImGui::gui_layout::end_horizontal ();
    mixImGui::gui_layout::end_vertical ();
}
References mixImGui::gui_layout::begin_horizontal(), mixImGui::gui_layout::begin_vertical(), mixImGui::gui_layout::end_horizontal(), mixImGui::gui_layout::end_vertical(), mixImGui::gui_layout::horizontal_space(), and mixImGui::gui_layout::text_label().
on_inspector_gui()
void mix::core::mixEntity::on_inspector_gui () override protected virtual
Implements mixImGui::i_guielement.
Definition at line 109 of file mixEntity.cpp.
{
}
on_scene_gui()
void mix::core::mixEntity::on_scene_gui () override protected virtual
Implements mixImGui::i_guielement.
Definition at line 113 of file mixEntity.cpp.
{
}
render()
void mix::core::mixEntity::render (mix::rendering::rendering_context * rendering) virtual
Definition at line 75 of file mixEntity.cpp.
{
    for (auto it = _components.cbegin (); it < _components.cend (); it++)
    {
        auto comp = (*it).get ();
        comp->render (rendering, static_cast<const mix::core::mixTransform*> (_transform.get ()));
    }
    for (auto it = _children.cbegin (); it < _children.cend (); it++)
    {
        auto ch = (*it).get ();
        ch->render (rendering);
    }
}
set_name()
void mix::core::mixEntity::set_name (std::string name)
Definition at line 52 of file mixEntity.cpp.
{
    _name = name;
}
update()
void mix::core::mixEntity::update () virtual
Reimplemented in mix::core::mixCamera.
Definition at line 57 of file mixEntity.cpp.
{
    _transform->update ();
    for (auto it = _components.cbegin (); it < _components.cend (); it++)
    {
        auto comp = (*it).get ();
        comp->update ();
    }
    for (auto it = _children.cbegin (); it < _children.cend (); it++)
    {
        auto ch = (*it).get ();
        ch->update ();
    }
}
Member Data Documentation
_children
std::vector<std::shared_ptr<mixEntity> > mix::core::mixEntity::_children protected
Definition at line 50 of file mixEntity.h.
_components
std::vector<std::unique_ptr<mixComponent> > mix::core::mixEntity::_components protected
Definition at line 51 of file mixEntity.h.
_is_enabled
bool mix::core::mixEntity::_is_enabled { true } protected
Definition at line 45 of file mixEntity.h.
_is_visible
bool mix::core::mixEntity::_is_visible { true } protected
Definition at line 46 of file mixEntity.h.
_name
std::string mix::core::mixEntity::_name protected
Definition at line 48 of file mixEntity.h.
_parent
std::weak_ptr<mixEntity> mix::core::mixEntity::_parent protected
Definition at line 49 of file mixEntity.h.
_transform
std::unique_ptr<mixTransform> mix::core::mixEntity::_transform
Definition at line 22 of file mixEntity.h.
The documentation for this class was generated from the following files:
mixEntity.h
mixEntity.cpp