Mix Model Viewer: mix::editor::windows::hierarchy_window Class Reference
mix::editor::windows::hierarchy_window Class Reference
#include <hierarchy_window.h>
Public Member Functions
void render () override
void on_editor_window_size_changed_impl (const vec2i &size) override
hierarchy_window (std::string window_name, mixImGui::window_rect r)
~hierarchy_window ()
Public Member Functions inherited from mixImGui::gui_window
gui_window (std::string window_name, window_rect r, window_flags flags=window_flags::None)
virtual void render ()
void disable ()
void enable ()
virtual void on_editor_window_size_changed (const vec2i &size)
void set_title (std::string s)
void set_contrainsts (window_rect constraints)
void clear_constraints ()
void set_positioning (window_positioning wp)
Static Public Member Functions
static void initialize (const vec2i &size)
Private Attributes
bool _visible_entities = true
bool _visible_lights = true
bool _visible_cameras = true
i_guielement * _selected_entity
Additional Inherited Members
Protected Member Functions inherited from mixImGui::gui_window
void begin ()
void end () const
void rescale (const vec2i &size)
void set_position (const vec2i &pos)
vec2i get_position () const
vec2i get_size () const
virtual void on_editor_window_size_changed_impl (const vec2i &size)=0
virtual void on_window_resized (const vec2i &old_size, const vec2i &new_size)
window_flags get_flags () const
Protected Attributes inherited from mixImGui::gui_window
bool _is_open = true
std::string _window_name
window_rect _rect
window_rect _constraints
Detailed Description
Definition at line 11 of file hierarchy_window.h.
Constructor & Destructor Documentation
hierarchy_window()
mix::editor::windows::hierarchy_window::hierarchy_window (std::string window_name, mixImGui::window_rect r)
Definition at line 87 of file hierarchy_window.cpp.
: mixImGui::gui_window (window_name,
                        r,
                        mixImGui::window_flags::MenuBar | mixImGui::window_flags::NoCollapse |
                        mixImGui::window_flags::NoMove)
{
    _selected_entity = nullptr;
}
References _selected_entity.
~hierarchy_window()
mix::editor::windows::hierarchy_window::~hierarchy_window ()
Definition at line 97 of file hierarchy_window.cpp.
{
}
Member Function Documentation
initialize()
void mix::editor::windows::hierarchy_window::initialize (const vec2i & size) static
Definition at line 101 of file hierarchy_window.cpp.
{
    // TODO: MAKE ALL INT ARGUMENTS AS W, H TO VEC2
    auto WINDOW_BEGIN_POS = 0.85f;
    auto WINDOW_SIZE = 0.15f;
    auto rect = mixImGui::window_rect ((int) (size.x * WINDOW_BEGIN_POS), 0, (int) (size.x * WINDOW_SIZE),
                                       static_cast<int> (size.y * 0.75f));
    mixImGui::mixGui::add_window (new editor::windows::hierarchy_window (std::string ("Hierarchy"), rect));
}
References mixImGui::mixGui::add_window().
on_editor_window_size_changed_impl()
void mix::editor::windows::hierarchy_window::on_editor_window_size_changed_impl (const vec2i & size) override virtual
Implements mixImGui::gui_window.
Definition at line 78 of file hierarchy_window.cpp.
{
    auto WINDOW_BEGIN_POS = 0.85f;
    auto WINDOW_SIZE = 0.15f;
    auto width = size.x * WINDOW_SIZE;
    rescale (vec2i (width, static_cast<int> (size.y * 0.75f)));
    set_position (vec2i (size.x * WINDOW_BEGIN_POS, 0));
}
render()
void mix::editor::windows::hierarchy_window::render () override virtual
Reimplemented from mixImGui::gui_window.
Definition at line 4 of file hierarchy_window.cpp.
{
    auto scene = mix::mixEditor::_instance->get_active_scene ();
    if (scene)
    {
        set_title (scene->get_root ()->get_name ());
        begin ();
        gui_layout::begin_vertical ();
        gui_layout::begin_selectable_list (_selected_entity);
        gui_layout::collapsing_label ("Cameras", &_visible_cameras);
        if (_visible_cameras)
        {
            gui_layout::add_selectable (static_cast<i_guielement*> (scene->get_main_cam ()));
            gui_layout::render_added_selectables ();
        }
        //gui_layout::collapsing_label ("Entities", &_visible_entities);
        if (gui_layout::tree_node ("Entities", -1, false, true, false))
        {
            auto children = scene->get_root ()->get_children ();
            for (int i = 0; i < children.size (); i++)
            {
                bool is_node = children.at (i)->get_children ().size();
                if (gui_layout::tree_node (children.at (i)->get_name ().c_str (), i, false, false, !is_node))
                {
                    if (gui_layout::begin_drag_drop_source())
                    {
                        gui_layout::set_drag_drop_payload ("ENTITY_", children.at (i).get (), sizeof (mix::core::mixEntity));
                        gui_layout::end_drag_drop_source ();
                    }
                    if (gui_layout::begin_drag_drop_target ())
                    {
                        auto data = gui_layout::accept_drag_drop_payload ("ENTITY_");
                        if (data)
{
                            auto target = reinterpret_cast<mix::core::mixEntity*> (data);
                            if (target != children.at (i).get())
{
                                //children.at (i).get ()->add_child (target);
                            }
                        }
                        gui_layout::end_drag_drop_target ();
                    }
                    if (gui_layout::is_double_clicked())
                    {
                        mix::mixEditor::_instance->get_active_scene ()->get_main_cam ()->look_at (children.at (i)->_transform->get_position());
                    }
                    if (is_node)
                    {
                        gui_layout::tree_pop ();
                    }
                }
            }
        }
        _selected_entity = gui_layout::end_selectable_list ();
        if (_selected_entity != nullptr)
        {
            _selected_entity->on_gui ();
        }
        gui_layout::end_vertical ();
        end ();
    }
}
References mix::mixEditor::_instance, _selected_entity, _visible_cameras, mixImGui::gui_layout::accept_drag_drop_payload(), mixImGui::gui_layout::add_selectable(), mixImGui::gui_window::begin(), mixImGui::gui_layout::begin_drag_drop_source(), mixImGui::gui_layout::begin_drag_drop_target(), mixImGui::gui_layout::begin_selectable_list(), mixImGui::gui_layout::begin_vertical(), mixImGui::gui_layout::collapsing_label(), mixImGui::gui_window::end(), mixImGui::gui_layout::end_drag_drop_source(), mixImGui::gui_layout::end_drag_drop_target(), mixImGui::gui_layout::end_selectable_list(), mixImGui::gui_layout::end_vertical(), mixImGui::gui_layout::is_double_clicked(), mixImGui::i_guielement::on_gui(), mixImGui::gui_layout::render_added_selectables(), mixImGui::gui_layout::set_drag_drop_payload(), mixImGui::gui_window::set_title(), mixImGui::gui_layout::tree_node(), and mixImGui::gui_layout::tree_pop().
Member Data Documentation
_selected_entity
i_guielement* mix::editor::windows::hierarchy_window::_selected_entity private
Definition at line 27 of file hierarchy_window.h.
_visible_cameras
bool mix::editor::windows::hierarchy_window::_visible_cameras = true private
Definition at line 26 of file hierarchy_window.h.
_visible_entities
bool mix::editor::windows::hierarchy_window::_visible_entities = true private
Definition at line 24 of file hierarchy_window.h.
_visible_lights
bool mix::editor::windows::hierarchy_window::_visible_lights = true private
Definition at line 25 of file hierarchy_window.h.
The documentation for this class was generated from the following files:
hierarchy_window.h
hierarchy_window.cpp