Mix Model Viewer: mix::assetsystem::default_assets Class Reference
mix::assetsystem::default_assets Class Reference
#include <default_assets.h>
Static Public Member Functions
static const mix::assetsystem::mixTexture * get_asset_default_icon (const mix::assetsystem::mixAsset_item *item)
Private Member Functions
default_assets ()=delete
Detailed Description
Definition at line 12 of file default_assets.h.
Constructor & Destructor Documentation
default_assets()
mix::assetsystem::default_assets::default_assets () private delete
Member Function Documentation
get_asset_default_icon()
const mix::assetsystem::mixTexture * mix::assetsystem::default_assets::get_asset_default_icon (const mix::assetsystem::mixAsset_item * item) static
Definition at line 5 of file default_assets.cpp.
{
    ASSERT (mixAsset_manager::instance != nullptr);
    if (const mix::assetsystem::mixTexture* t = dynamic_cast<const mix::assetsystem::mixTexture*>(item))
    {
        return t;
    }
    auto name = asset_types::get_asset_default_icon_name (item->get_extension());
    auto asset = mixAsset_manager::instance->get_asset_with_base_name<mix::assetsystem::mixTexture> (name).get ();
    return asset;
}
References ASSERT, mix::assetsystem::asset_types::get_asset_default_icon_name(), mix::assetsystem::mixAsset_manager::get_asset_with_base_name(), mix::assetsystem::mixAsset_item::get_extension(), and mix::assetsystem::mixAsset_manager::instance.
The documentation for this class was generated from the following files:
default_assets.h
default_assets.cpp