Mix Model Viewer: mix::core::mixTransform Struct Reference
mix::core::mixTransform Struct Reference
#include <mixTransform.h>
Public Member Functions
mixTransform ()
mixTransform (vec3 pos)
mixTransform (vec3 pos, vec3 rot)
mixTransform (vec3 pos, vec3 rot, vec3 scale)
~mixTransform ()
mixTransform (mixTransform &&move)=delete
mixTransform (const mixTransform &copy)=delete
void set_position (vec3 v)
void set_local_position (vec3 v)
void set_rotation (vec3 v)
void set_scale (vec3 v)
void translate (vec3 v)
void scale (vec3 v)
void look_at (const vec3 &pos)
void rotate_around (float x, float y, float z)
void update ()
mat4 get_model_mat () const
vec3 up () const
vec3 forward () const
vec3 right () const
float yaw () const
float pitch () const
float roll () const
vec3 get_position () const
vec3 get_local_position () const
vec3 get_rotation () const
vec3 get_scale () const
Private Member Functions
void update_vectors ()
Private Attributes
vec3 _position
vec3 _local_position
vec3 _rotation
vec3 _scale
vec3 _forward
vec3 _up
vec3 _right
bool _is_dirty
Detailed Description
Definition at line 20 of file mixTransform.h.
Constructor & Destructor Documentation
mixTransform() [1/6]
mix::core::mixTransform::mixTransform ()
Definition at line 66 of file mixTransform.cpp.
                                   : mixTransform (vec3 (0), vec3 (0), vec3 (1))
{
}
mixTransform() [2/6]
mix::core::mixTransform::mixTransform (vec3 pos)
Definition at line 70 of file mixTransform.cpp.
                                           : mixTransform (pos, vec3 (0), vec3 (1))
{
}
mixTransform() [3/6]
mix::core::mixTransform::mixTransform (vec3 pos, vec3 rot)
Definition at line 74 of file mixTransform.cpp.
                                                     : mixTransform (pos, rot, vec3 (1))
{
}
mixTransform() [4/6]
mix::core::mixTransform::mixTransform (vec3 pos, vec3 rot, vec3 scale)
Definition at line 78 of file mixTransform.cpp.
: _position{ pos }, _local_position{ 0 }, _rotation{ rot }, _scale{ scale }, _is_dirty{ true }
{
    update ();
}
References update().
~mixTransform()
mix::core::mixTransform::~mixTransform ()
Definition at line 84 of file mixTransform.cpp.
{
}
mixTransform() [5/6]
mix::core::mixTransform::mixTransform (mixTransform && move) delete
mixTransform() [6/6]
mix::core::mixTransform::mixTransform (const mixTransform & copy) delete
Member Function Documentation
forward()
vec3 mix::core::mixTransform::forward () const inline
Definition at line 51 of file mixTransform.h.
            {
                return _forward;
            }
References _forward.
get_local_position()
vec3 mix::core::mixTransform::get_local_position () const inline
Definition at line 81 of file mixTransform.h.
            {
                return _local_position;
            }
References _local_position.
get_model_mat()
mat4 mix::core::mixTransform::get_model_mat () const
Definition at line 56 of file mixTransform.cpp.
{
    mat4 m (1.0f);
    m = rotate (m, _rotation.x, transform::right);
    m = rotate (m, _rotation.y, transform::up);
    m = rotate (m, _rotation.z, transform::forward);
    m = glm::translate (m, _position);
    return m;
}
References mix::transform::forward, mix::transform::right, rotate(), and mix::transform::up.
get_position()
vec3 mix::core::mixTransform::get_position () const inline
Definition at line 76 of file mixTransform.h.
            {
                return _position;
            }
References _position.
get_rotation()
vec3 mix::core::mixTransform::get_rotation () const inline
Definition at line 86 of file mixTransform.h.
            {
                return _rotation;
            }
References _rotation.
get_scale()
vec3 mix::core::mixTransform::get_scale () const inline
Definition at line 91 of file mixTransform.h.
            {
                return _scale;
            }
References _scale.
look_at()
void mix::core::mixTransform::look_at (const vec3 & pos)
Definition at line 38 of file mixTransform.cpp.
{
    auto d = normalize (-pos + _position);
    _rotation.y =radians_to_degrees ((float) atan (d.x / (-d.y)));
    _rotation.x = radians_to_degrees ((float) atan (pow (d.x, 2) + pow (d.y, 2)));
    _is_dirty = true;
    update ();
}
References normalize(), and radians_to_degrees().
pitch()
float mix::core::mixTransform::pitch () const inline
Definition at line 66 of file mixTransform.h.
            {
                return _rotation.y;
            }
References _rotation.
right()
vec3 mix::core::mixTransform::right () const inline
Definition at line 56 of file mixTransform.h.
            {
                return _right;
            }
References _right.
roll()
float mix::core::mixTransform::roll () const inline
Definition at line 71 of file mixTransform.h.
            {
                return _rotation.z;
            }
References _rotation.
rotate_around()
void mix::core::mixTransform::rotate_around (float x, float y, float z)
Definition at line 48 of file mixTransform.cpp.
{
    _rotation.x += x;
    _rotation.y += y;
    _rotation.z += z;
    _is_dirty = true;
}
scale()
void mix::core::mixTransform::scale (vec3 v)
Definition at line 34 of file mixTransform.cpp.
{
}
set_local_position()
void mix::core::mixTransform::set_local_position (vec3 v)
Definition at line 10 of file mixTransform.cpp.
{
    _local_position = v;
    _is_dirty = true;
}
set_position()
void mix::core::mixTransform::set_position (vec3 v)
Definition at line 4 of file mixTransform.cpp.
{
    _position = v;
    _is_dirty = true;
}
References _is_dirty, and _position.
set_rotation()
void mix::core::mixTransform::set_rotation (vec3 v)
Definition at line 16 of file mixTransform.cpp.
{
    _rotation = v;
    _is_dirty = true;
}
set_scale()
void mix::core::mixTransform::set_scale (vec3 v)
Definition at line 22 of file mixTransform.cpp.
{
    _scale = v;
    _is_dirty = true;
}
translate()
void mix::core::mixTransform::translate (vec3 v)
Definition at line 28 of file mixTransform.cpp.
{
    _position += v;
    _is_dirty = true;
}
up()
vec3 mix::core::mixTransform::up () const inline
Definition at line 46 of file mixTransform.h.
            {
                return _up;
            }
References _up.
update()
void mix::core::mixTransform::update ()
Definition at line 88 of file mixTransform.cpp.
{
    if (_is_dirty)
    {
        update_vectors ();
        _is_dirty = false;
    }
}
update_vectors()
void mix::core::mixTransform::update_vectors () private
Definition at line 97 of file mixTransform.cpp.
{
    auto _yaw = yaw ();
    auto _pitch = pitch ();
    _forward.x = cos (degrees_to_radians (_yaw)) * cos (degrees_to_radians (_pitch));
    _forward.y = sin (degrees_to_radians (_pitch));
    _forward.z = sin (degrees_to_radians (_yaw)) * cos (degrees_to_radians (_pitch));
    _forward = normalize (_forward);
    _right = normalize (cross (_forward, transform::up));
    _up = normalize (cross (_right, _forward));
}
References cross(), degrees_to_radians(), normalize(), and mix::transform::up.
yaw()
float mix::core::mixTransform::yaw () const inline
Definition at line 61 of file mixTransform.h.
            {
                return _rotation.x;
            }
References _rotation.
Member Data Documentation
_forward
vec3 mix::core::mixTransform::_forward private
Definition at line 106 of file mixTransform.h.
_is_dirty
bool mix::core::mixTransform::_is_dirty private
Definition at line 110 of file mixTransform.h.
_local_position
vec3 mix::core::mixTransform::_local_position private
Definition at line 101 of file mixTransform.h.
_position
vec3 mix::core::mixTransform::_position private
Definition at line 100 of file mixTransform.h.
_right
vec3 mix::core::mixTransform::_right private
Definition at line 108 of file mixTransform.h.
_rotation
vec3 mix::core::mixTransform::_rotation private
Definition at line 103 of file mixTransform.h.
_scale
vec3 mix::core::mixTransform::_scale private
Definition at line 104 of file mixTransform.h.
_up
vec3 mix::core::mixTransform::_up private
Definition at line 107 of file mixTransform.h.
The documentation for this struct was generated from the following files:
mixTransform.h
mixTransform.cpp